### PR TITLE
Circular Games app category icon

### PR DESCRIPTION
**Pull request by palob**
Added a Numix Circle icon for the Games app category
applications-games

### CODE REVIEW

**Comment by Foggalong** [comment]
We still haven't decided if we want Circular icons for categories which why it's all still inconsistent. Hold the fort on this one :)

**Comment by palob** [comment]
Alright, here is an alternative which probably scales better:
applications-games1

**Comment by palob** [comment]
Deferred.

**Comment by Foggalong** [comment]
@palob fancy submitting the first of those as a solution to [this](https://github.com/numixproject/numix-icon-theme-circle/issues/1688)?

**Pull request closed without merging**
