### PR TITLE
Icon for Pentobi

### PR DESCRIPTION
**Pull request by palob**
A board game
http://sourceforge.net/projects/pentobi/

**Original icon:**
Icon=pentobi
pentobi-ori

**Pushed icon:**
pentobi

More 3Dish alt:
pentobi1b

### CODE REVIEW

**Comment by Foggalong** [comment]
The second one look very nice! The background is a bit blegh though. Either needs to be lighter or darker to make the contrast a bit better

**Comment by palob** [comment]
Lighter or darker?
pentobi999
pentobi9

**Comment by Foggalong** [comment]
Darker :+1:

**Comment by palob** [comment]
Pushed :+1:

**Pull request merged**
