### PR TITLE
Icon for fs-uae

### PR DESCRIPTION
**Pull request by gregorydk**
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2913

### CODE REVIEW

**Comment by palob** [comment]
How does it look with only one check and the letters above it?

**Comment by gregorydk** [comment]
If I do that it's not the logo any more, as seen on https://fs-uae.net/

**Comment by palob** [comment]
The way it is however it clashes with the guidelines w.r.t. both size and gradients on the symbol.

Is it recognisable at smaller sizes?

**Comment by gregorydk** [comment]
Made the logo smaller, it was indeed a bit big (from 32px to 24px width).

**Comment by palob** [comment]
Now the "S" isn't aligned anymore.
misaligned

Moreover there are unneeded nodes which oddly enough even show up in the preview.
preview

**Comment by Foggalong** [comment]
Just for future reference, the colours used in the gradient were also too brash, there are a few loose nodes in the tick symbol, and the text still wasn't aligned to grid. I'm going to merge it and tidy it up because I need to get rid of all the pulls for something we're doing :)

**Comment by gregorydk** [comment]
I know about the colours, but they're the colours from the original logo and didn't want to change that. About the nodes, no idea which ones, I checked before.

**Comment by Foggalong** [comment]
@gregorydk The nodes were in the tick part, usually doubled up on top of one another and hidden away. If you can modify the colours while not straying too far it's worth it to keep a nicer icon. In this case though, [the original Amiga logo](https://upload.wikimedia.org/wikipedia/en/a/a7/Amiga_Logo_1985.svg) provided some softer colours :)

**Comment by gregorydk** [comment]
Ah, I wasn't aware of that logo. I based it on the [fs-uae logo](https://plus.google.com/photos/116108691672931109163/albums/profile/5749218744563325170). I'll see what I can do.

**Comment by palob** [comment]
@Foggalong already chaged the colours accordingly :)

**Pull request merged**
