### PR TITLE
Icon for Translator. Fixes #1465

### LINKED ISSUE #1465: Translator icon
Translator is a new application in elementary 
the icon line : 
Icon=translator

The default icon 
capture du 2015-01-17 01 03 19

### PR DESCRIPTION
**Pull request by palob**
Icon for Translator, issue #1465
Pushed:
translator
Alternative background:
translator1

### CODE REVIEW

**Comment by ChuckDaniels87** [comment]
I like pulled one. Just a suggestion: what about colouring each bubble different?

**Comment by Foggalong** [comment]
Gonna pull this in for now, but feel free to do more merges if you play around with the bubble colours

**Comment by palob** [comment]
Like this:
translator-colours

**Comment by ChuckDaniels87** [comment]
Yep, cool. Try a different colour in the blue one, maybe purple or yellow?

**Comment by palob** [comment]
translator-colours2

**Comment by ChuckDaniels87** [comment]
Seems fine, what do you think?

**Comment by palob** [comment]
Maybe a more neutral background?

**Comment by ChuckDaniels87** [comment]
I prefer blue background, try brighter purple or yellow.

**Pull request merged**
