### PR TITLE
Icon for AltYo

### PR DESCRIPTION
**Pull request by palob**
https://github.com/linvinus/AltYo

altyo
altyo-numix

### CODE REVIEW

**Comment by Foggalong** [comment]
Could we possibly have a bit more contrast between the bottom symbol shape and the background?

**Comment by palob** [comment]
But of course :) Pushed this
altyo-numix

Alt
altyo2

**Comment by bil-elmoussaoui** [comment]
+1 for the Alt

**Comment by Foggalong** [comment]
The alt is nice, but I'll take one that looks nice and follows the symbol format any day :heart:

**Pull request merged**
