### PR TITLE
Add the Name To The License

### PR DESCRIPTION
**Pull request by TommyPujol06**
See line 656

### CODE REVIEW

**Comment by TommyPujol06** [comment]
I know that it is NOT important but I also have seen that there are no License in the top of the files as you say : 
> You've misunderstood what that part to the license is for. It's not designed to be filled in by developers there in the LICENSE file, but used as a header for any code elsewhere the project uses. We do that in the main script and the test files.

**Comment by Foggalong** [comment]
@TommyPujol06 That's because this repo isn't for code, it's for packaging. The actual build repo file [have such headers](https://github.com/numixproject/numix-core/blob/master/gen.py#L3-L10).

**Comment by TommyPujol06** [comment]
@Foggalong Ok, but why don't just add it is stupid.

**Comment by Foggalong** [comment]
@TommyPujol06 I think your comment is missing a word, but I'll take two stabs at what it might've been.

If you're meaning "why don't we just add our own name to the license file", it's because that's not what that part of the file is for. In fact if (any part) of the GPL license is modified you're [in direct violation of the first requirement of the license](https://github.com/numixproject/numix-icon-theme-circle/blob/master/LICENSE#L6-L7). This is a small difference between GPL and other licenses like MIT which have explicit places for such modifications. The template header you modify in this pull request should first be copied into the file on which copyright is desired, then filled out with the project details.

Iif you're meaning "why don't we just add the header to the icon files themselves", there are a few reasons but the simplest is it would unnecessarily add ~2MB to the theme. Applying the GPL to art and SVGs is something a of grey area; we're not really GPLing the "code" of each icon but the designs used. In hindsight, if we were doing the project again we'd probably use CC-BY-SA for the artwork instead.

Licensing on FOSS projects is (perhaps unfortunately) something I've spent a lot of time on over the last few years so if you do have any questions about it happy to answer either here or by email if you'd prefer.

**Pull request closed without merging**
