### PR TITLE
SVG cleanup + KDE/Qt fixes

### PR DESCRIPTION
**Pull request by palob**
Did some SVG cleanup by removing invisible shadow elements, path unions of shadow elements and executing [your SVG cleaning script](https://github.com/numixproject/numix-tools/blob/master/numix-tools/svgclean) (found it, finally :) + fixed numerous small issues (like broken strokes, stroke -> path conversions, miscoloured shadows).

A welcome side effect is that it fixes the baseplate part of the KDE/Qt issues #2016.

Total file size reduction: 4.1 MB.

### CODE REVIEW

**Comment by palob** [comment]
Forgot some, will add them later.

**Comment by Foggalong** [comment]
The reason we stopped using our own cleaner was because the reduction to a single line started causing problems with elements in icons disappearing. Is that not a problem anymore?

**Comment by palob** [comment]
All pre-mid 2014 were in the single-line state anyway. I tested with several distros and didn't come accross missing elements. 
Maybe it was about elements missing in the GitHub preview?

**Comment by Foggalong** [comment]
No, it was actual missing elements from the icons. One I remember was the Rhythmbox speaker kept vanishing. It's the reason we stopped cleaning icons in that way. You sure that's not happened here?

**Comment by palob** [comment]
Maybe it was some grouping issue? I'll do some even more intense testing :)

**Comment by palob** [comment]
Do you remember when exactly this vanishing did occur?

**Comment by Foggalong** [comment]
It was when we last tried using it, I think early this year

**Comment by palob** [comment]
So I went through the icons over and over again (using different distros / file managers / image viewers) but I couldn't make out any defective icon.

**Comment by wa4557** [comment]
@palob I'll try to verify this too :)

**Comment by palob** [comment]
@wa4557 Thanks a lot :)

**Comment by bil-elmoussaoui** [comment]
I verified this too using elementary OS freya and everything works fine! 
capture du 2015-06-03 12 45 32

**Comment by wa4557** [comment]
I looked at all the icons. No problem when using the new icons at Ubuntu 15.04 + unity

**Comment by dirtydancing** [comment]
I checked with Arch/GNOME Shell: no visible breakage with the new icons here either.

However, I noticed one thing about Inkscape: I checked with `unsettings.svg`, an icon that has caused some problems with the gradient before, cf. https://github.com/numixproject/numix-icon-theme-circle/pull/2052. When opening with Inkscape, with the current icon I was able to easily modify the gradient colour. In contrast, with the new icon, for some reason I could not modify the gradient colour at all. Now, this might be just this icon, or this might be just me using Inkscape, but maybe someone can reproduce this effect?

In addition, as the metadata etc. are gone in the cleaned up icons, in Inkscape they do not open maximised or with the grid visible anymore, but I figure this is intended.

**Comment by dirtydancing** [comment]
One more aspect for your consideration: to me, when opening the new .svg files with a text editor, the code does not necessarily look "cleaner", but rather more "compressed" (into one line). This would make troubleshooting details within the code itself more difficult.

I am just wondering (not opposed to this change): Is there a way to "decompress" the code again? And is there any advantage to the single line compression besides reducing the file size?

**Comment by palob** [comment]
Thanks to all for your testing.
@dirtydancing I can reproduce the *unsettings.svg* thing. I have to set the colour to solid and to gradient again in order to edit it. Don't know what that's about.

Unravelling the single-line SVG should be fairly trivial, it's XML and each line starts and ends with **<**/**> respectively. Of course after opening an SVG in Inkscape and saving it, you get back to the uncopressed variant, losing all optimisations.
I don't know which option in the SVG cleaning script exactly causes the one-line files, maybe it's possible without that one.

**Comment by palob** [comment]
``svgcleaner-cli --help`` shows *Save file with only required whitespace and newlines* for ``--compact-output``

**Comment by dirtydancing** [comment]
Confirmed that the .svg code turns back to "uncompressed" after saving an icon file with Inkscape.

I would agree that it makes sense to use the cleaner script in a way that preserves the separate lines.

For some reason, I am still stuck with this "bug" that lets me change the gradient colour visibly in Inkscpape, but not visibly e.g. in Nautilus or Thunar. So this is not limited to Ubuntu, but also appears in Arch. Somehow, there is a "doubling" of the stop-color/opacity for the gradients when I change the gradient colour. Well, I figure as @Foggalong has already said earlier, to not get bogged down by this.

Screenshot of the code
vlc_gradient

VLC (vlc2.svg) icon change in Inkscape (different colours)
vlc2_inkscape

versus e.g. Nautilus (no difference displayed for vlc2.svg)
vlc2_nautilus

But this thing apparently is not related to the present changes, so I guess this is safe to ignore here :)

**Comment by palob** [comment]
Yeah, we had to deal with this "gradient bug" earlier.

**Comment by Foggalong** [comment]
@palob RE your comment in the other merge thread, I didn't think this was mergeable yet because of the gradient bug? Feel free to correct me if otherwise!

**Comment by palob** [comment]
Sorry, which thread exactly are you referring to?

**Comment by dirtydancing** [comment]
@palob I believe @Foggalong is referring to this comment of yours: https://github.com/numixproject/numix-icon-theme-circle/pull/2247#issuecomment-109418687

@Foggalong I believe the above mentioned "gradient bug" has nothing to do with the clean-up filed here by @palob. This "bug" has appeared before, and this clean-up as far as I can tell has no influence on that (neither for the better nor for the worse). imo this pull request here is ready to be merged.

**Comment by Foggalong** [comment]
@palob @dirtydancing I thought you were discussion a problem about the usettings gradient being corrupted, caused by this cleanup?

**Comment by palob** [comment]
We were indeed. The gradient wasn't corrupted in terms of the outer apperance. The glitch was with editing.
*unsettings.svg* had been a strange one before with big filesize despite the simple shape and colours. I've copied the symbol to anpther baseplate and now I can edit the gradient without the need to set a solid colour first + the filesize is halved.

**Comment by palob** [comment]
Regarding the single-line SVGs: You can restore the multiline layout (while losing the SCG cleanups) in an easy way by batch-running any Inkscape-CLI option (for instance ``inkscape --vacuum-defs``).

If desired I could do this and run the SVG cleaning script afterwards. This way we'd get cleaned and Qt-fixed files while retaining readability. (I'd go through the icons again afterwards :).

**Comment by Foggalong** [comment]
@palob I'd prefer multiline readout yeah :) Thanks for looking at this, it's very helpful!

**Comment by palob** [comment]
Alright, I'll probably do it as a new PR later.

**Comment by palob** [comment]
Yay, I've found a way to fix the "gradient bug" for good on all icons. I'll do it tomorrow and fix the ``svgclean`` script accordingly.

**Comment by dirtydancing** [comment]
Great! :+1:

**Comment by Foggalong** [comment]
@palob feel free to submit a pull request to the numix-tools repo with the fix :D

**Comment by palob** [comment]
A little explanation:

In a SVG with a fresh baseplate gradient (no gradient bug) a baseplate gradient looks like this:

```SVG
    <linearGradient
       id="linearGradient3794">
      <stop
         style="stop-color:#5c431c;stop-opacity:1;"
         offset="0"
         id="stop3796" />
      <stop
         style="stop-color:#6b4e21;stop-opacity:1;"
         offset="1"
         id="stop3798" />
    </linearGradient>
```

Both stop colours and opacities are defined as ``style``.

After applying the current unfixed *svgclean* script it would look like this:
```SVG
  <linearGradient id="linearGradient3800" y1="28" x2="0" y2="20" gradientUnits="userSpaceOnUse">
   <stop stop-color="#5c431c" stop-opacity="1"/>
   <stop offset="1" stop-color="#6b4e21" stop-opacity="1"/>
  </linearGradient>
```
Here stop colours and opacities are defined seperately as ``stop-color`` and ``stop-opacity``.
Now when editing the gradient colours in Inkscape the changes are saved as ``style`` after the values for ``stop-color`` and ``stop-opacity`` which are left untouched.
The "gradient bug" occurs because the latter two values take precedence for what's displayed in the file manager / image viewer / web browser.

The simple fix:
The ``svgcleaner-cli`` option ``--join-style-atts`` merges the ``stop-color`` and ``stop-opacity`` values into ``style`` attributes.

**Comment by palob** [comment]
I'll apply the fix in a new PR

**Pull request closed without merging**
