### PR TITLE
Vivaldi Browser Icon

### LINKED ISSUE #1510: Icon for Vivaldi browser [$5]
Hi, a Numix-Circle icon is missing for Vivaldi browser.

Icon line: `Icon=vivaldi`

Original icon:

vivaldi

<bountysource-plugin>
---
There is a **[$5 open bounty](https://www.bountysource.com/issues/8125486-icon-for-vivaldi-browser?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
Vivaldi Browser Icon, closes #1510

icons

### CODE REVIEW

**Comment by Foggalong** [comment]
Needs to be down 1px to counter the illusion

**Comment by ChuckDaniels87** [comment]
Done. :smile:
icons

**Comment by Foggalong** [comment]
You're a star

**Comment by ChuckDaniels87** [comment]
Thanks! :+1:

**Comment by dirtydancing** [comment]
Sweet addition, thanks!

**Comment by sergioad** [comment]
thank you very much @ChuckDaniels87, I am a Vivaldi active user, it is my favorite browser so I am so happy to see this icon :smile: BTW @Foggalong I hope you update the squae icons soon, I can not use any icon theme with not this icon and I love the Numix square icons

**Pull request merged**
