### PR TITLE
Icon for PlayItSlowly. Fixes #1569

### LINKED ISSUE #1569: Icon for PlayItSlowly
A free/open source application for manipulating speed and pitch of audio files.

Icon=playitslowly
playitslowly

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8531425-icon-for-playitslowly?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by palob**
Icon for PlayItSlowly. Fixes #1569
Pushed:
playitslowly
Alt:
playitslowly1c
playitslowly6

### CODE REVIEW

**Comment by Foggalong** [comment]
3rd, though the symbol needs to be 1px right and 1px down to counter the illusion

**Comment by palob** [comment]
playitslowly6b

**Comment by Foggalong** [comment]
Much better! Push and I'll pull

On 26 February 2015 14:14:32 GMT+00:00, palob <notifications@github.com> wrote:
>playitslowly6b
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/numixproject/numix-icon-theme-circle/pull/1574#issuecomment-76184421

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by palob** [comment]
Already pushed :-)

**Pull request merged**
