### PR TITLE
File size optimisation + minor fixes

### PR DESCRIPTION
**Pull request by palob**
Diff looks savage... :grimacing: but only cosmetic and under-the-hood changes

+ Invisible optimisation
Some of my contributed icons (and other recently contributed ones) hadn't undergone Inkscape's "unused def cleaning" (from within the GUI or ``inkscape --vacuum-defs`` CLI option).
So I carried this out + deleted invisible cruft/shadow elements where it helped.

 Replaced redundant icons with symlinks:
 sigram --> telegram
 cd-desklets, footnote --> screenlets

**Total saved disk space: 4.2 MB**

+ Minor visal fixes
 Fixed shadows (colour, missing elements):
 byobu, friends, frogatto, gajim, screenlets, web-reddit, xnconvert, xnview

 Fixed alignment:
 openteacher, sauerbraten

 Fixed envelope glitch:
 geary

 Fixed font not converted to path:
 gperiodic

### CODE REVIEW

**Comment by Foggalong** [comment]
I'd check this, noticed a few errors such as missing symbols. Splitting it up into separate pull requests would be appreciated too, makes it easier to verify.

**Comment by palob** [comment]
Hmm, what do you mean by "missing symbols". I see all icons displayed properly even after deleting the icon thumbnail cache.

**Comment by palob** [comment]
To trim the diff I could divide it into a few single commits / PRs like *icons from start to F*, *F to K*, ... or something

**Comment by Foggalong** [comment]
Not sure why my comment didn't send :( The commit is too big to test everything, but because you're a trusted contributor I thought I'd just make a few random checks to make sure it looked okay. Of the 7-8 I opened 2 or 3 just didn't have any symbols, only a base plate. Though I can't remember all of them, [Runner.svg](https://github.com/palob/numix-icon-theme-circle/blob/optimisation/Numix-Circle/48x48/apps/Runner.svg) was one of them.

**Comment by palob** [comment]
That's odd. I do see it on my local branch. However there was an issue of a duplicate of *Runner.svg* which I fixed in the last commit.

Any backward incompatible changes introduced with Inkscape 0.91 or a newer Cairo version?

**Comment by palob** [comment]
Don't see broken icons in cloned branch.

**Comment by Foggalong** [comment]
Not that I'm aware of :(

**Comment by palob** [comment]
Maybe it's an issue of how Github renders SVGs?

**Comment by palob** [comment]
OK, I do get the empty baseplates when viewing with a web browser.
Amongst the affected are aarddict, abrowser, artha, awesomenauts, byobu, entangle, freeciv, friends, frogatto, gajim,  gcompris, gperiodic, rubyripper, sauerbraten, screenlets, various steam icons,  supertuxkart, web-reddit, zeal

--> the icons where I edited the shadow / deleted invisible (non outline-defining) shadow elements

However some icons I didn't touch throw an error message in Firefox and blinken+goobox don't show up correctly despite I didn't edit the shadows. And some icons with edited shadows do show up correctly.

I'm stumped as to what's the reason here.

**Comment by palob** [comment]
Now when I view the icons above in Numix Circle master (i. e. the unedited versions) in Firefox either I am presented with an error message and the raw source or I'd be looking at the plain baseplate/broken symbols as well.

Just have a look at some of my PRs, for instance #1504 #1405 #1408 #1627 #1662 #1400 #1386 #1373 #1300 #1283
The rich diff shows broken symbols for all. IIRC this might be icons where I incorporated edited parts of existing Numix icons. Have the Numix Circle icons ever been processed in any way?

For edited icons made by Ismael are displayed correctly in Github / the browser.

**Comment by Foggalong** [comment]
Huh, that's very weird. Anyway, I'm going to trust that you've done a good job in editing this together. Don't let me down ;)

**Pull request merged**
