### PR TITLE
LinSSID icon

### LINKED ISSUE #1313: icon for LinSSID [$5]
http://sourceforge.net/projects/linssid/

Icon=LinSSID

image

<bountysource-plugin>
---
There is a **[$5 open bounty](https://www.bountysource.com/issues/6389068-icon-for-linssid?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
LinSSID icon, fixes #1313

icon

Any suggestions?

### CODE REVIEW

**Comment by palob** [comment]
Haven't got a design idea so far but the file must be called *LinSSID.svg* case-sensitively (or a symlink) to address the reported icon line correctly.

**Comment by ChuckDaniels87** [comment]
The icon seems hardcoded at the source, maybe some distros are patching the package. AUR package seems hardcoded, what about other distros guys?

**Comment by ChuckDaniels87** [comment]
I've created a symlink.

**Comment by hlechner** [comment]
Now I've extracted the .deb file from the developer's sourceforge and the .desktop is also hardcoded.

I couldn't find it inside [ubuntu packages](http://packages.ubuntu.com/) nor [fedora package](https://admin.fedoraproject.org/pkgdb/) the LinSSID application.

It seems only that the issue's creator have "misspelled" the icon name. But the symlink is not bad idea anyway.

**Comment by Foggalong** [comment]
Watch having multiple colours layered on top of one another, makes for poorer quality edges

**Comment by ChuckDaniels87** [comment]
I'll clean it later and remove the symlink.

**Comment by palob** [comment]
@hlechner It's probably (correctly) pasted from the launcher file. There are other occasions of capital letters in icon lines.

**Comment by ChuckDaniels87** [comment]
Should I keep the symlink?

**Comment by palob** [comment]
Well, it's a matter of a few Bytes so I'd say yes in case of doubt :smile:

**Comment by Foggalong** [comment]
Aye, keep symlink :)

**Comment by ChuckDaniels87** [comment]
Fixed :wink:

icon

**Pull request merged**
