### PR TITLE
Add icon for Reportbug

### PR DESCRIPTION
**Pull request by gregorydk**
Made debian-swirl.svg which is used by Reportbug (https://wiki.debian.org/reportbug)

### CODE REVIEW

**Comment by Foggalong** [comment]
We already have `distributor-logo-debian.svg` so the icon just needs to be a symlink to that

**Comment by gregorydk** [comment]
I know, but instead of ending up with 10 identical icons, I wanted some variation, so I inverted the colours, which also makes it resemble the real icon/logo more.

**Comment by Foggalong** [comment]
It's a nice idea but not really necessary for two very niche icons

**Comment by gregorydk** [comment]
It's fine. You can make it a symlink then.

**Comment by gregorydk** [comment]
Do I need to open a new issue for this?

**Comment by Foggalong** [comment]
Not at all, [already been fixed](https://github.com/numixproject/numix-icon-theme-circle/commit/e061730f90851a4df774cc2004a63c52fe9e1f78) :)

**Comment by gregorydk** [comment]
Awesome :-)

**Pull request closed without merging**
