### PR TITLE
Storm United Icon

### LINKED ISSUE #1999: Storm United (Steam)
Game: __Storm United__
AppID: __332970__

steam_icon_332970

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11448748-storm-united-steam?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
Storm United, closes #1999

icon

I am not sure about this one, any suggestion?

### CODE REVIEW

**Comment by ChuckDaniels87** [comment]
Minor light fix:
icon

**Comment by palob** [comment]
Maybe a little less saturated background + the eye colour more like the original one?

**Comment by Foggalong** [comment]
A really like this! Game icons are notoriously difficult to do while adhering to guidelines. I'd be happy to merge it as is, but don't mind if you want to play around a bit. I do really like the background colour though

**Comment by dirtydancing** [comment]
I like this one as it is, too. But as you asked for suggestions: how about somehow making the head less static and more dynamic by modifying the perspective in a way that makes is look "more 3D", how do I say this? more like coming up from below, if possible at all. Well, I am running into terminology difficulties here, maybe you know what I am saying :)

**Comment by ChuckDaniels87** [comment]
More 3D-ish... :stuck_out_tongue_closed_eyes: 

How about this one?
icon

**Comment by dirtydancing** [comment]
Wow, phantastic! To me, this is a much improved version. This is closer to the original, more "massive", more dynamic, more "menacing" and more powerful. A very worthy Numix-Circle No. 2000 :)

**Comment by ChuckDaniels87** [comment]
@dirtydancing I'm glad you like it!! This game is now in Beta but will be _Free to Play_ when they release it. We could play some games and have some fun (p.e. Contributors vs. Numix staff, :stuck_out_tongue_winking_eye: ).

**Comment by dirtydancing** [comment]
Haha, good call! I am actually not that much of a gamer, and probably I would need to get a new machine before that, given that I am still running a regular "old-school" ThinkPad T500 :), but hey.

As to this icon: when I look at the old version and the new version next to each other in regular size 48x48, the old version looks like some guy who forgot to shave, whereas the new one is just wow! :)

**Comment by ChuckDaniels87** [comment]
LOL

**Pull request merged**
