### PR TITLE
3 new icons & a symlink

### LINKED ISSUE #2611: Spec Ops: The Line (Steam)
Name: Spec Ops: The Line
AppID: 50300
Icon: spec_ops__the_line_icon_by_jonywallker-d5n731m
Notes: Game about war and its atrocities, set in the middle-east.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27462485-spec-ops-the-line-steam?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by MrTimscampi**
Adds icons for:

* Sakura Spirits (Steam)
* Origin (Wine)
* Spec Ops: The Line (Steam)

Adds symlinks for:

* GNOME Games

Fixes #2611 and #2627

### CODE REVIEW

**Comment by MrTimscampi** [comment]
I just noticed Inkscape had it's own SVG format, so the third commit corrects that.

**Comment by ChuckDaniels87** [comment]
It is a good practise separate icons in one pull request each if they are not related. You can use git branches for each one.

**Comment by MrTimscampi** [comment]
Oh, sorry :p 
I saw a message in another pull that mentioned keeping the number of pull requests low while waiting for another important merge, so I assumed doing this was fine.

I'll separate the future ones in different branches & PRs from now on :)

**Comment by ChuckDaniels87** [comment]
If @Foggalong or someone from Numix staff told you just listen to him, I'm just a contributor :yum:. I think one icon (or several symlinks) per pull request is better because you can merge them individually.

**Comment by MrTimscampi** [comment]
I just assumed it would be easier to merge if I kept everything inside one pull request :)

But it's actually a lot easier to manage my updates and for the team to see exactly what I'm committing if I separate them, so I'll do that from now on :) (I've already made a few new PRs since then)

Of course, if someone from the staff tells me to keep my PRs together (I have a pretty huge list of stuff to make, so I'll generate a lot of pull requests), I'll go back to combining my commits for different icons :)

**Comment by ChuckDaniels87** [comment]
:+1:

**Comment by Foggalong** [comment]
Yeah, generally 1 icon per pull request. Makes reviews easier :)

**Comment by palob** [comment]
Some comments on the icons:

**9AD6_Origin.0.svg**
+ Ideally the symbol width is an even integer for best alignment to the pixel grid, even for "circularish" ones

**Comment by MrTimscampi** [comment]
I cleaned up the torn edges on Spec Ops' icon. Size of the icon is still around 74Kb, though (Still the heaviest in the directory. Next one is Left 4 Dead with 48kB).
I could further simplify the design by removing some holes and maybe some of the stars, if needed (Currently, number of stars is accurate to the real-life flag).

**Comment by palob** [comment]
Actually, a fringe doesn't need more than 3 nodes.

**Comment by MrTimscampi** [comment]
Spec Ops' icon is now significantly smaller, at 29.3kB.
A lot of (unnecessary) detail has been removed, hidden shapes have been removed and cleaned up, number of stars was reduced from 50 to 3 (They looked like a mess at 48px anyway) and visible paths have been cleaned too (The fringes, but also other paths that had an unnecessary high number of nodes because of boolean operations)

**Comment by palob** [comment]
Much better now :+1: Maybe less red/white stripes?

In order to get the filesize down you can delete all the invisible shadow elements (or do a path union of all shadow elements and remove unneeded nodes). You only need a single path for the shadow.

**Comment by MrTimscampi** [comment]
Got it down to 20.5kB by doing a Union on the shadow paths and removing some stripes.

**Comment by palob** [comment]
20.5 is alright :)

**Comment by Foggalong** [comment]
@MrTimscampi Just giving this a run through:

##### Origin
Make the circle in the centre aligned to grid, try a colour (possibly a yellow) for the background to brighten it up a bit.

##### Sakura
Same with background, try a very light pink.

##### Spec Ops
All good. Props on the creative icon :)

**Comment by Foggalong** [comment]
@MrTimscampi Make sure you keep that `S` constant!

**Comment by MrTimscampi** [comment]
Must've been my mouse acting up when changing the L value, sorry about that (I really should check more before doing my commits ^^' )

**Comment by Foggalong** [comment]
Still showing up as not constant :(

**Comment by Foggalong** [comment]
Gonna merge this and correct the value manually since it would seem @MrTimscampi has vamooshed.

**Comment by Foggalong** [comment]
I cannot get these L values to stay put O.o is this an Inkscape bug?

**Comment by palob** [comment]
Is it this bug where you can't set the colours for the gradient stops in Inkscape?
If yes it's best to take a fresh baseplate from another icon and recolour it.

**Comment by Foggalong** [comment]
Ah shoot, that would be the one yeah

**Comment by palob** [comment]
I found this bug by pure coincidence in ``jiten.svg`` a few moments ago when reviewing #2755.
Either there are more or that's where @MrTimscampi took the baseplate from.

**Comment by Foggalong** [comment]
Is this connected to the botched MSC icons then?

**Comment by palob** [comment]
Not that I'd know. Haven't investigated the SVG code so far.

**Comment by Foggalong** [comment]
I really love SVG but I wish it wasn't so difficult to work with sometimes

**Comment by palob** [comment]
``steam_icon_50300.svg`` for some reason crashes Inkscape.

**Comment by Foggalong** [comment]
Working fine on my end. Do you get any error if you launch it from a terminal?

**Comment by palob** [comment]
Seems to be an Inkscape bug (memory access error).

**Comment by Foggalong** [comment]
Huh, weird. Does it happen for any other icons or just that one?

**Comment by palob** [comment]
Only for that one. Can't seem to find the crash dump.

**Comment by Foggalong** [comment]
Do you get a crash with Left4Dead? Thinking it could be to do with it being a big SVG

**Comment by palob** [comment]
Looks like there was something wrong with the baseplate again. After removing it from the SVG code the icon opens.

**Comment by Foggalong** [comment]
Damn baseplates -_-

**Comment by palob** [comment]
Given that it is yellowish maybe he took ``jiten.svg`` (fixed in my PR) again.

**Pull request merged**
