### PR TITLE
More cleanup & alignment fixes

### PR DESCRIPTION
**Pull request by palob**

### CODE REVIEW

**Comment by Foggalong** [comment]
What are you using for your SVG cleaning? I tried to get svgcleaner-cli working the other day but to no avail :(

**Comment by palob** [comment]
The Numix [svgclean script](https://github.com/numixproject/numix-tools/blob/master/numix-tools/svgclean). It's just ``svgcleaner-cli`` with the right option chosen.

Alternatively you can save as optimised SVG directly from Inkscape.
You have to disable the ``CSS to XML`` option though in order to prevent the gradient bug as discussed [here](https://github.com/numixproject/numix-icon-theme-circle/pull/3024#issuecomment-214532473).

**Comment by Foggalong** [comment]
@palob Did you build svgcleaner-cli from the source? I'm trying to get it installed on Ubuntu 16.04 but with no joy

**Comment by palob** [comment]
I use ``svgcleaner 0.6.2`` from the AUR, so basically built from source, yes.

**Comment by Foggalong** [comment]
Ah damn. I'll look up the AUR build see if that works any better

**Pull request merged**
