### PR TITLE
Icon for youdao-dict

### PR DESCRIPTION
**Pull request by Revolution1**
icon for the translation and dictionary app [youdao-dict](http://cidian.youdao.com/index-linux.html)

before: image

after: youdao-dict-after

### CODE REVIEW

**Comment by palob** [comment]
Can you change the symbol size to ``24x24`` and place it at ``X13 Y11``?

This improves the looking glass pixel grid alignment. It's almost perfect now and can be easily fixed:

The yellowish circles are the new ones.

**Comment by Revolution1** [comment]
No problem.

 It is the first time I contribute to Numix project. I just changed the
original SVG from square to circle.

And I will fix it soon.

Thank you for your cautious attitude to such an awesome project.

2016-06-04 18:17 GMT+08:00 Vincent Bermel <notifications@github.com>:

**Comment by palob** [comment]
Huh, are there icons in Square which aren't in Circle?

**Comment by Foggalong** [comment]
@palob I don't recognise this icon as being from square :/

**Pull request merged**
