### PR TITLE
Icon for Hexalate. Fixes #1608

### LINKED ISSUE #1608: Icon for Hexalate
A colour matching game
http://gottcode.org/hexalate/

Icon=hexalate
hexalate

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8998033-icon-for-hexalate?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by palob**
Icon for Hexalate. Fixes #1608
hexalate-with shadow

### CODE REVIEW

**Comment by Foggalong** [comment]
Nice, but really doesn't fit in with the Numix guidelines. How does it look with the gradients removed?

**Comment by palob** [comment]
Not particularly good, or does it?
hexalate-alt

**Comment by Foggalong** [comment]
Of the two, definitely the emblem one

**Comment by palob** [comment]
Alright, pushed this one:
hexalate-alt

**Pull request merged**
