### PR TITLE
Icon for Monster RPG 2

### PR DESCRIPTION
**Pull request by Eleuin**
monster-rpg-2
monster-rpg-2-2

### CODE REVIEW

**Comment by palob** [comment]
You need to move the baseplate down such that the "bevel shadow" is visible.

**Comment by Eleuin** [comment]
yeah, i reapplied the symbol to another baseplate. i actually never noticed this, thanks btw

**Comment by palob** [comment]
Oh no, you fell victim to the "gradient bug". The baseplate shows up correctly in Inkscape but is displayed red in file managers / image viewers.

To solve this, change the baseplate filling to a solid colour or to nothing and do the gradient from scratch. That's always the way to go when changing a gradient unfortunately.

**Comment by Eleuin** [comment]
ok, that was weird... and definitely something i should remember for later. i've just never seen this before <.<

**Comment by Eleuin** [comment]
@Foggalong any thoughts?

**Comment by Foggalong** [comment]
I can't check SVGs very thoroughly on my tablet, which is where I do most of my labelling, commenting, etc. It's a very nice icon, though the symbol possibly needs moving down 1 or 2px to account fo

**Comment by Eleuin** [comment]
yeah, its rather top heavy. i can move the symbol down a bit

**Comment by Foggalong** [comment]
Excellent! :D

**Pull request merged**
