### PR TITLE
Calf

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
LV2/DSSI/LADSPA plug-ins suite and standalone JACK host.

icon

Website: http://calf-studio-gear.org/
Based on the [original icon](https://github.com/calf-studio-gear/calf/blob/master/icons/calf_icon.svg).

### CODE REVIEW

**Comment by ChuckDaniels87** [comment]
Is it better in with a green background?

icon

**Comment by ChuckDaniels87** [comment]
I've reduced symbol size to 28px and changed background to green:

icon

**Comment by Foggalong** [comment]
I'm not sure on this, the use of outlines feels a bit unnumixy

**Comment by ChuckDaniels87** [comment]
Nose and eyes outline?

**Comment by Foggalong** [comment]
I think that's it yeah

**Comment by ChuckDaniels87** [comment]
What about this? 
icon


If I completely remove eye outline it looks pretty strange.

**Comment by palob** [comment]
Looks better. 
I agree, the remaining eye outline could only got rid off by colouring either the eyes or the skin greyish.

**Comment by ChuckDaniels87** [comment]
I tried that @palob but looks awful and it is almost not noticeable at smaller sizes.

**Comment by palob** [comment]
@Foggalong In case you didn't notice: He pushed the changes.
I'm however wondering whether the contrast was better with the darker orange background.

**Comment by ChuckDaniels87** [comment]
I can try with darker green later today.

**Comment by ChuckDaniels87** [comment]
Better?
icon

**Comment by Foggalong** [comment]
Yeah that's looking nicer. Push and we're good to go :)

**Comment by ChuckDaniels87** [comment]
It is already pushed. :+1:

**Pull request merged**
