### PR TITLE
Icon for KFolderSync

### PR DESCRIPTION
**Pull request by palob**
http://kde-apps.org/content/show.php/KFolderSync?content=164092

kfoldersync
kfoldersync-numix

### CODE REVIEW

**Comment by Foggalong** [comment]
Those colours definitely need swapping out. It'd be possible to get red green and blue working, but not those particular shades.

**Comment by palob** [comment]
You're right, that is one nasty colour combination :weary: 
Maybe one of those?
kfoldersync2
kfoldersync2b
kfoldersync2c

**Comment by Foggalong** [comment]
Of those the last one is definitely the best, though I'm not 100% sure on it. I'll merge it though if you're happy with it :)

**Comment by palob** [comment]
Pushed this one
kfoldersync4

**Comment by Foggalong** [comment]
I'm less sure of this one. The contrast is back to clashing a bit too much.

**Comment by palob** [comment]
This?
kfoldersync5

**Comment by Foggalong** [comment]
Yeah, I can go for that.

**Comment by palob** [comment]
Pushed :+1:

**Pull request merged**
