### PR TITLE
Icon for gnome-appfolders-manager

### PR DESCRIPTION
**Pull request by palob**
https://github.com/muflone/gnome-appfolders-manager

gnome-appfolders-manager
gnome-appfolders-manager-numix

Alt:
gnome-appfolders-manager0

### CODE REVIEW

**Comment by Foggalong** [comment]
I'm fine with this design, - I really love the alt! But it's also going to need icons in numix-folders with each of the folder styles too :)

**Comment by palob** [comment]
Going with the alt then?

**Comment by Foggalong** [comment]
Aye :)

**Comment by palob** [comment]
Pushed :+1:

**Pull request merged**
