### PR TITLE
Icon for Allcast Receiver Chrome app

### PR DESCRIPTION
**Pull request by m-e-h**

### CODE REVIEW

**Comment by Foggalong** [comment]
That's quite nice design, and I'd definitely be interested in merging :) To fit in with the rest of the icons though, can you shrink the striped circle to 30px and move the RSS icon acordingly (possibly keeping it the same size?). Thanks :)

**Comment by m-e-h** [comment]
No problem. I'll revise tomorrow.

**Comment by Foggalong** [comment]
Thanks :D

**Comment by Foggalong** [comment]
@m-e-h you still wanting to do this? The icon looks like it would be a good addition to the theme :)

**Comment by m-e-h** [comment]
Yeah, sorry bout that. I just revised it on my laptop but it looks like it got bigger. May have to wait till I get to my desktop tomorrow.

**Comment by Foggalong** [comment]
Ah, not a problem :)

**Comment by m-e-h** [comment]
I'm just gonna close this and open a new request

**Pull request closed without merging**
