### PR TITLE
Removes circular icons that are also in base

### LINKED ISSUE #2164: Cinnamon Menu Consistency Issue
numixgitissue

Issue is illustrated in above image.

I would give an example symlink but there doesn't seem to be a Numix Circle equivalent for that controller icon, I do however know that the name of that icon is "applications-games". This also doesn't seem to be the only "applications-" prefix icon that is missing an icon or symlink either, fixing this would probably prevent further consistency issues.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/17120143-cinnamon-menu-consistency-issue?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by wa4557**
Fixes #2164 and #1930

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
You forgot ``` applications-php.svg" this icon is used for
``` php.svg 
phpmyadmin.svg```

**Comment by wa4557** [comment]
Yeah that was intenional because there's no corresponding icon in base

**Comment by bil-elmoussaoui** [comment]
the best thing is to remove it and report it in base? as this icon is only used in Software center (i guess)

**Comment by wa4557** [comment]
Yeah I'll probably do this in a pull request afterwards. I don't want to put too much effort in creating a php categories icons, if this PR isn't merged

**Comment by palob** [comment]
This might have been discussed before but are ``help.svg`` and ``info.svg`` actually app icons?
Are they used for any system settings plug?

Problem is, they are shown in the interfaces of some programs.

**Comment by Foggalong** [comment]
Gonna close this because these kind of things are gonna have to be considered on a per app basis. Hardcoded stuff is complicated

**Comment by wa4557** [comment]
Makes kind of sense but concerning #2164 and #1930 what's then the preferred way to fix it? Adding the missing icons to circle or removing those icons from circle (then this PR would have made sense after all)

**Comment by Foggalong** [comment]
I honestly have no idea. Whenever the topic has come up within Numix we've been unable to agree. Maybe it's something we should ask G+ users?

**Comment by wa4557** [comment]
Sounds like a plan :+1:

**Pull request closed without merging**
