### PR TITLE
Icon for Angry IP. Fixes #2233

### LINKED ISSUE #2233: Icon for Angry IP Scanner
network scanner
http://angryip.org/

Icon=ipscan
ipscan

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/19150505-icon-for-angry-ip-scanner?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by palob**
Fixes #2233
ipscan-icon

### CODE REVIEW

**Comment by Foggalong** [comment]
Maybe make the whole background the green? Not sure on it in its current form

**Comment by palob** [comment]
Played with this but didn't like it as much:
ipscan0

**Comment by Foggalong** [comment]
Going back to the original one then? Maybe drop the gradient from the stick and the border from the bolt

**Comment by palob** [comment]
Like this:
ipscan5

**Comment by Foggalong** [comment]
Yeah, I think that's more in line with the rest of the icons :)

**Comment by palob** [comment]
Done :+1:

**Pull request merged**
