### PR TITLE
Enhanced icon for digiKam

### PR DESCRIPTION
**Pull request by palob**
Made this icon for digiKam:
digikam

Replaces the current icon (symlink) which is also used for several screenshot/camera apps:
digikam_alt

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Could you symlink this with the camera app?

**Comment by palob** [comment]
Well the camera app is for the integrated camera or webcams , isn't it?

**Comment by bil-elmoussaoui** [comment]
Yes; i ve reported that the screenshot app and the webcam app have the same icon :)

**Comment by palob** [comment]
Maybe a tad brighter?
digikam-b

**Comment by palob** [comment]
Slightly simpler design
digikam-c

**Comment by Foggalong** [comment]
@palob Can we have [this one](https://cloud.githubusercontent.com/assets/7050624/6285361/1f300a16-b8fb-11e4-96b7-5e63e4091aa4.png)?

**Comment by palob** [comment]
OK, pushed.
digikam

**Pull request merged**
