### PR TITLE
JDownloader Symbol fix

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
JDownloader Symbol, 26px->28px, vertical 2px down. 

icons

Original pull request #1708.

### CODE REVIEW

**Comment by Foggalong** [comment]
Can I see it 1px left?

**Comment by ChuckDaniels87** [comment]
Looks misaligned:

icons

**Comment by Foggalong** [comment]
Good call

**Comment by palob** [comment]
Wow, lots of shiny additions this weekend :+1:

**Comment by ChuckDaniels87** [comment]
Too much free time, :P.

**Pull request merged**
