### PR TITLE
Icon for Wolfenstein: The New Order

### PR DESCRIPTION
**Pull request by Eleuin**
Yet another icon for this series, this leaves just Wolfenstein 3D left

### CODE REVIEW

**Comment by palob** [comment]
Compared to existing icons the colours look brash to me. Try a less saturated (lower S value in the HSL notation) and maybe brighter baseplate and use white L249 instead of pure white.

**Comment by Eleuin** [comment]
there we go
wolftno

**Comment by palob** [comment]
Still a bit dark and saturated but let's see what's @Foggalong's view

**Comment by Eleuin** [comment]
ill resubmit this PR, just had a commit i wanted to whack because i don't need silly commits clogging up the repo :>

**Pull request closed without merging**
