### PR TITLE
Additional fix for #1716

### PR DESCRIPTION
**Pull request by hlechner**
Sorry, I forgot to mention the "p7zip" on issue #1716

GenericName=7-Zip File Manager
Icon=p7zip

### CODE REVIEW

**Comment by hlechner** [comment]
Someone knows what I did wrong?

The link is created, but it seems a "broken link" when I cloned the repository.

From bash it seems to be correct:
```
# ls -lah | grep 7z
-rw-r--r-- 1 root root  40K Mar 15 18:11 7zip.svg
lrwxrwxrwx 1 root root    8 Mar 15 18:11 7z.svg -> 7zip.svg
lrwxrwxrwx 1 root root    9 Mar 15 18:11 p7zip.svg -> 7zip.svg
```

image

image

It seems a "new line" in the link.

Maybe its a good time to learn how to use the git command line and avoid github editor. somebody knows how I can fix it?

**Comment by Foggalong** [comment]
How did you manage that? :P The command for creating a symlink is just `ln -s 7zip.svg p7zip.svg` - you seem to have somehow put a newline in there

**Comment by hlechner** [comment]
Actually I never managed it by my system, I just come in github interface click in "edit" and change it from there, but it seems that the github add a newline anyway.

I'll learn how I use git from command line then I send the right one in pull request

**Comment by Foggalong** [comment]
Oh right! Yeah, you can't do symlinks properly in GitHub. One of my first pull requests made the exact same error :P

**Pull request merged**
