### PR TITLE
New zanshin.svg

### PR DESCRIPTION
**Pull request by dirtydancing**
As discussed in https://github.com/numixproject/numix-icon-theme-circle/issues/2089, here is a new icon for Zanshin.

zanshin_proposed

in size 48x48
zanshin_48x48

### CODE REVIEW

**Comment by dirtydancing** [comment]
Made baseplate brighter for better contrast esp. when scaling down.

zanshin_proposed_new

Icon when scaled down to 50% (24x24):

zanshin_proposed_new_24x24

**Comment by Foggalong** [comment]
Symbol needs to be slightly further down, just 1 or 2 px

**Comment by dirtydancing** [comment]
Screenshot with zanshin.svg as above compared to 1px down and to 2px down. 2px down pushed :)

zanshin

**Comment by Foggalong** [comment]
2px down was the right call :)

**Pull request merged**
