### PR TITLE
Added scudcloud

### LINKED ISSUE #1810: Icon for  ScudCloud
Hi, 

Please add icon for ScudCloud.

ScudCloud: Icon=/opt/scudcloud/resources/scudcloud.png

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10225012-icon-for-scudcloud?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Ghokun**
Fixes #1810

### CODE REVIEW

**Comment by Foggalong** [comment]
There seems to be an error with your background gradient not registering properly in the saved icon, though it's fine in the original SVG. Try colour picking to fill the whole shape, and then re-gradienting from that.
screenshot - 300315 - 22 01 58
Also, watch that your straight lines are aligned to grid otherwise they'll come out a bit blury
screenshot - 300315 - 22 01 42
Great work though, a nice addition :D

**Comment by Ghokun** [comment]
I will try to fix them tomorrow

**Comment by Ghokun** [comment]
Same tumbnail issue appears in the freeminer icon, can you check?

**Comment by Foggalong** [comment]
Yeah, I pushed the fix for the freeminor icon after I merged it :) remember to git  pull!

**Pull request merged**
