### PR TITLE
Fixes #1187

### LINKED ISSUE #1187: Icon for PlaneShift
Name=PlaneShift
Icon=/opt/PlaneShift/support/icons/psicon.png
screenshot from 2014-09-29 21 09 41

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/4956998-icon-for-planeshift?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by wa4557**
#1187

### CODE REVIEW

**Comment by Foggalong** [comment]
Move the symbol down 1px and that's good to go :)

**Comment by wa4557** [comment]
Here we go :)

**Comment by Foggalong** [comment]
Now I've had chance to download it an examine properly there are a few other things that need fixing.

Horizontal and vertical lines always need to be aligned to grid, otherwise they'll look très blury.
screenshot_2015-04-25_14-02-51

The GitHub gradient problem strikes again too :P
screenshot_2015-04-25_14-03-13

**Comment by wa4557** [comment]
Aww man...

**Comment by Foggalong** [comment]
Yeah, sorry :(

**Comment by wa4557** [comment]
Not your fault, if I'm too stupid :) Ok should be ok now imp

**Comment by Foggalong** [comment]
It's not a problem!

**Pull request merged**
