### PR TITLE
Icon for ReText. Fixes #1425

### LINKED ISSUE #1425: Icon for Retext
A new icon for retext 

a powerfull markdown editor

retext

Thanks

### PR DESCRIPTION
**Pull request by palob**
Icon for ReText, issue #1425
retext

### CODE REVIEW

**Comment by palob** [comment]
Rounded slit, rounded stroke.
retext-neu

**Comment by palob** [comment]
Maybe slightly less saturated colours for the pencil?
retext-less-satur

**Comment by Foggalong** [comment]
Aye, less saturated looks better.

**Comment by palob** [comment]
Pushed :+1:

**Comment by Foggalong** [comment]
Thanks!

**Pull request merged**
