### PR TITLE
iViewer icon

### LINKED ISSUE #1603: Icon for iViewer
I would like to ask for an icon : 
iViewer : https://github.com/Philip-Scott/iViewer
the icon is hardcoded; but i already reported this , the icon line will be fixed in the next update!
the original icon :
icon48
I will add the icon line as soon as i get the update!
Thank you 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8932504-icon-for-iviewer?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
iViewer icon, closes #1603

icons

### CODE REVIEW

**Comment by Foggalong** [comment]
Nice! :D move the symbol down 2px and I'll merge :)

**Comment by ChuckDaniels87** [comment]
Is one pix down enough?

icons

**Comment by Foggalong** [comment]
Yeah, that'll do fine :)

**Comment by bil-elmoussaoui** [comment]
Thanks <3

**Pull request merged**
