### PR TITLE
Icon for Umbrello

### LINKED ISSUE #1994: Icon for Umbrello
UML Modeller
https://www.kde.org/applications/development/umbrello/

Icon=umbrello
umbrello

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11401882-icon-for-umbrello?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by palob**
Icon for Umbrello. Fixes #1994
Pushed:
umbrello
Alt:
umbrello9a
umbrello9f

### CODE REVIEW

**Comment by palob** [comment]
Maybe better without the outlines?
umbrello0

**Comment by Foggalong** [comment]
Go with blue and white and without the outlines :)

**Comment by Foggalong** [comment]
Go with blue and white and without the outlines :)

**Comment by palob** [comment]
Alright, blue/white, triangular shape, outlines fixed :)

**Pull request merged**
