### PR TITLE
Icon for pumpa

### PR DESCRIPTION
**Pull request by gregorydk**
Icon for pumpa (https://pumpa.branchable.com/), a pump.io client.

### CODE REVIEW

**Comment by palob** [comment]
The baseplate colour is quite harsh and dark, isn't it?

**Comment by gregorydk** [comment]
If I make it lighter there's not enough contrast with the actual icon, unless I use light grey. But I don't want to make yet another icon with a grey baseplate. Any suggestions? Green baseplate?

pumpa-green

**Comment by palob** [comment]
I think the contrast looks OK on the revised one + the grid doesn't look that aggressive.
Maybe even a tad lighter / more yellowish.

A minor issue: there are a few unneeded nodes on the shadow.

**Comment by gregorydk** [comment]
I don't see the unneeded nodes.

New:
pumpa

**Comment by palob** [comment]
Yep, looks good to me :+1:. What do you think?
I was referring to the nodes between the edges :)

**Comment by Foggalong** [comment]
Icons that use pixel art need 100% aligning to grid. They'll just end up looking like rubbish otherwise. The symbol is a bit too big too. We recommend 24px<sup>2</sup> for symbol size but this one is 30px by 25px. Reduction to about 26px by 22px would make it fit the guidelines a bit better

**Comment by gregorydk** [comment]
The current size is 12 x 10 "pixels". So 24 x 20 fits better.

**Comment by Foggalong** [comment]
24x10 would be acceptable, though it'll look a little small

**Comment by gregorydk** [comment]
If I make it 26 px wide, the height is 21.667 px. Not really ideal I think. So 24 x 20 or 30 x 25 are round numbers.

**Comment by Foggalong** [comment]
24px would be the ideal, but remember the rest of the lines have to be aligned to grid too

**Pull request merged**
