### PR TITLE
Symlink for gscreenshot

### PR DESCRIPTION
**Pull request by palob**
https://github.com/thenaterhood/gscreenshot

### CODE REVIEW

**Comment by Foggalong** [comment]
Please symlink screenshot tools to the screenshot icon rather than the camera icon. When we address the associated issue about them being non-distinct this will make things easier :)

**Comment by palob** [comment]
As far as I can see that's where other screenshot tools are symlinked against as well. I could change the link to ``hotshots.svg`` for instance.

**Comment by palob** [comment]
Did it.

**Comment by Foggalong** [comment]
Oh damn, I was thinking there was an `accessories-screenshot` but I seem to have been mistaken

**Comment by palob** [comment]
Revert to ``accessories-screenshot``?

**Pull request closed without merging**
