### PR TITLE
added a nicer spotify icon

### PR DESCRIPTION
**Pull request by markbaas**

### CODE REVIEW

**Comment by palob** [comment]
I take it it is the old one recoloured?
The baseplate needs a gradient (L10 lighter at the top), the shadow is buggy (miscoloured, needs to be black with A25 or 10% opacity) and try to use white with L249 instead of pure white.

**Comment by Foggalong** [comment]
I'd not realised Spotify had updated their logo. For reference, this is what it looks like now

 spotify

It's worth noting though that the icon of their [Andoid app](https://play.google.com/store/apps/details?id=com.spotify.music) hasn't been upated yet. Can anyone confirm if they've changed their desktop icon too?

**Comment by Ghokun** [comment]
Mac icon hasn't changed

**Comment by Foggalong** [comment]
@Ghokun Cool. Any idea for Linux? I'm imagining it's a similar sory

**Comment by bil-elmoussaoui** [comment]
There's a new beta version [More informations](http://ubuntuhandbook.org/index.php/2015/06/install-spotify-client-1-x-beta-ubuntu/) But i don't think that icon has changed

**Comment by Foggalong** [comment]
Can anyone confirm this _on Linux_?

**Comment by bil-elmoussaoui** [comment]
I just installed the latest beta and the icon still the same

**Comment by Foggalong** [comment]
@bil-elmoussaoui Thanks! :D Gonna mark this as wontfix and close. If they decide to make their new logo their icon also we'll look at merging it :)

**Comment by markbaas** [comment]
Why won't fix. My PR never had anything to do with the new spotify logo. The current logo included is the standard spotify icon and imo does not fit nicely in the numix icon theme. I just added a logo that I believe goes along better with the other icons.

**Comment by markbaas** [comment]
@foggalong Check the logo on the page @bil-elmoussaoui has shared: http://ubuntuhandbook.org/index.php/2015/06/install-spotify-client-1-x-beta-ubuntu/ The logo is white on green. That looks much better than the black on green that is currently in the numix-icon-theme.

**Comment by Foggalong** [comment]
We're not talking the logo though, we're talking the icon for the program itself. But anyway, If you want it considering for merging as an enhancement first address the problems [brought up by @palob](https://github.com/numixproject/numix-icon-theme-circle/pull/2242#issuecomment-108587006) so that it does indeed fit in with the rest of the Numix Circle theme.

**Comment by markbaas** [comment]
Then why would you close the PR? I was going to address the problems brought up by @palob, doesn't make sense to close the PR for me to create a new one.

**Comment by Foggalong** [comment]
With 7 days without acknowledging his comment I assumed you weren't :P we quite often get pull requests from new contributors who never respond to queries or comments after their initial commit.

But anyway, you can still push commits to close pull requests. Once the fixes have been pushed I'll reopen it for consideration

**Comment by palob** [comment]
@markbaas I'll prepare a big PR tonight (hopefully) which will repair the original icon your changes are based upon. I recommend you rebase your fork then and work against the clean icon.

**Comment by markbaas** [comment]
Okay perfect!

**Comment by Ghokun** [comment]
iOS icon has changed 
photo_2015-06-15_16-38-34

**Comment by brittyazel** [comment]
I can confirm that the Windows version of spotify is carrying the new colored logo, and the Android and IOs versions are sporting it as well

**Pull request closed without merging**
