### PR TITLE
Icon for JMeter

### LINKED ISSUE #1062: Icon for JMeter
Icon for Apache JMeter

icon name: jmater

jmeter

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/3590618-icon-for-jmeter?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by palob**
Fixes #1062

Pushed:
jmeter1

Alt:
jmeter

### CODE REVIEW

**Comment by palob** [comment]
@Foggalong How about this?

**Comment by Foggalong** [comment]
I like it, but I think the blue might be a but too harsh. Not sure

**Comment by palob** [comment]
Here's a bit lighter colours
jmeter000

**Comment by palob** [comment]
Even lighter?
jmeter-light

**Comment by ChuckDaniels87** [comment]
Maybe less saturation?

**Comment by Foggalong** [comment]
Yeah it's not so much the colours on the feather, but the colour of the background

**Comment by palob** [comment]
Ah, I see. This is what I'm at now:
jmeter-new
jmeter-new2

**Comment by Foggalong** [comment]
Top one is good with me :+1:

**Comment by palob** [comment]
Pushed :+1:

**Comment by ChuckDaniels87** [comment]
Much better, nice icon by the way!

**Pull request merged**
