### PR TITLE
readme: Update copr repo for fedora

### PR DESCRIPTION
**Pull request by ankitstarski**

### CODE REVIEW

**Comment by Foggalong** [comment]
I wasn't aware we'd renamed to repo? @satya164?

**Comment by bil-elmoussaoui** [comment]
Btw, i think that you should really guys look for someone to maintain the fedora repo. the latest update was a long time ago..i have to use the git version to get the latest updates..:(

**Comment by Foggalong** [comment]
We do have a few people that volunteered to do so, but there were some disagreements about release tagging which delayed things. It's be a help for me too since I use Korora as one of my main distros

**Comment by satya164** [comment]
@Foggalong Yeah, we did several months ago.
@bil-elmoussaoui Currently @sspreitzer is maintaining it

**Pull request merged**
