### PR TITLE
Icon for Tresorit

### PR DESCRIPTION
**Pull request by gregorydk**
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2281

### CODE REVIEW

**Comment by palob** [comment]
While fixing the baseplate issue you reintroduced the gradient bug.
Did you use Scour with the ``--disable-style-to-xml`` option. If yes and the problems still exits it's probably better not to use Scour.

**Comment by palob** [comment]
gradient bug is fixed :+1: but the merge conflict remains.

**Comment by Foggalong** [comment]
It also includes the file-manager icons which it shouldn't

**Comment by gregorydk** [comment]
That's weird, it's a separate branch.

**Comment by Foggalong** [comment]
Merge conflict fixed! The symbol is a bit too big though. Standard symbol size is 24-26px, but 30px for circular ones.

**Comment by Foggalong** [comment]
I fucked up and accidentally clicked the merge button. My bad! You're gonna have to make a new pull request & fix the symbol issue :( sorry!

**Comment by gregorydk** [comment]
24-26 is that the maximum for width and height? It's current size is 26x31.

**Comment by Foggalong** [comment]
Yeah, it's width and height. You can get away with going over with one of them if the other is a bit smaller, but not both

**Pull request merged**
