### PR TITLE
Icons for KBruch and KLettres

### PR DESCRIPTION
**Pull request by palob**
From the KDEdu suite
https://edu.kde.org/applications/

+ KBruch
Icon=kbruch
kbruch-ori

+ KLettres
Icon=klettres
klettres-ori

**Pushed icons:**
kbruch

klettres

### CODE REVIEW

**Comment by palob** [comment]
Whoops!

**Comment by Foggalong** [comment]
I think 19 seconds might be a new record :p

**Comment by palob** [comment]
Only 5 from what I was shown :boom:

**Comment by Foggalong** [comment]
:D

**Pull request merged**
