### PR TITLE
Icon for LuxRender

### LINKED ISSUE #2210: Icon for LuxRender
Free software rendering engine
http://www.luxrender.net/en_GB/index

luxrender.desktop
Icon=/usr/share/pixmaps/luxrender.svg
luxrender-ori

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/18429031-icon-for-luxrender?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by palob**
Fixes #2210

luxrender

### CODE REVIEW

**Comment by Foggalong** [comment]
Not quite sure on the colours for this. Maybe try a variant on the red from the outline as a background?

**Comment by palob** [comment]
luxrender0
luxrender0b
luxrender1
luxrender1b
luxrender2

Or even more red?

**Comment by Foggalong** [comment]
The second one is A+ :)

**Comment by palob** [comment]
luxrender0b
Up :+1:

**Pull request merged**
