### PR TITLE
PDF-Shuffler icon enhancement

### LINKED ISSUE #495: Icon for PdfShuffler missing [$5]
An icon for PdfShuffler is missing
Icon line says: Icon=pdfshuffler
The original icon:
pdfshuffler

<bountysource-plugin>
---
There is a **[$5 open bounty](https://www.bountysource.com/issues/5770298-icon-for-pdfshuffler-missing?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
PDF-Shuffler icon enhancement, fixes #495

icons

----------------------------------------------------------
Suggestions?

### CODE REVIEW

**Comment by Foggalong** [comment]
Ooo, nice idea! No idea if this will work, but how would a white PDF logo look on the blue?

**Comment by palob** [comment]
How about mirroring the orange sheet horizontally or mirriring it + putting it on the right and centering the blue sheet?

**Comment by ChuckDaniels87** [comment]
@Foggalong idea:
icons_1
icons_1_48

It doens't scale bad.

------------------------------
@palob idea:
icons_2

I personally prefer original one but this one doesn't look bad either.

**Comment by Foggalong** [comment]
Nice idea @palob, but gonna go with the first one. Job well done!

**Pull request merged**
