### PR TITLE
Icon for SpiderOakONE

### PR DESCRIPTION
**Pull request by gregorydk**
SpiderOak has been renamed to SpiderOakONE with version 6.0 and has a new icon.

### CODE REVIEW

**Comment by Foggalong** [comment]
Much better :D But your icon really needs aligning to grid - it'll show up blury without it

**Comment by Foggalong** [comment]
@gregorydk The horizontal and vertical lines in the arrow still aren't aligned to grid :(

screenshot_2015-07-23_18-15-34

**Comment by gregorydk** [comment]
Didn't want to change the proportion of the arrow. But I'll fix it.

**Comment by Foggalong** [comment]
You can afford to take the vertical lines to their nearest gridlines and the horizontal lines downwards to the nearest gridline. This will stop it looking blury and keep the proportions similar :)

**Pull request merged**
