### PR TITLE
Ion for Baka MPlayer

### PR DESCRIPTION
**Pull request by palob**
Another media player
http://bakamplayer.u8sand.net/

**Original icon**
Icon=baka-mplayer
baka-mplayer-ori

**Pushed Numix Circle icon:**
baka-mplayer

### CODE REVIEW

**Comment by Eleuin** [comment]
Only on linux would somebody name a music player "Baka MPlayer"

**Comment by palob** [comment]
It's cross-platform ...

**Comment by Eleuin** [comment]
ik palob but still, i laughed when i saw this

**Comment by palob** [comment]
Because of [this](https://en.wikipedia.org/wiki/Baka_%28word%29) or what?

**Comment by Eleuin** [comment]
haha, yeah. I never expected a developer to actually name a piece of software this, but its great. embrace the crazy :smiley:

**Comment by palob** [comment]
Same with *git*, eh?

**Pull request merged**
