### PR TITLE
SVG cleanup, icon fixes, gradient bug fix, KDE/Qt fixes

### PR DESCRIPTION
**Pull request by palob**
(continuation of #2240)

Quite a long night...

What did I do?
+ Removed invisible/redundant shadow elements, united some shadow paths
+ Fixed numerous small icon issues (misalignment, broken strokes, stroke-path conversion, miscoloured shadows, unneeded nodes, odd paths, grouping..). 
   For instance ``pencil.svg`` ``byobu.svg`` ``ForgedAllianceForever.svg`` ``diffuse.svg``.
+ Ran ``inkscape --vacuum-defs *.svg`` in the ``apps`` folder to restore the verbose multi-line layout for all icons (pre mid-2014 icons were one-liners).
+ Ran the Numix [svgclean script](https://github.com/numixproject/numix-tools/blob/master/numix-tools/svgclean) on all icons with the ``--compact-output`` option removed and the ``--join-style-atts`` option added. This prevents one-line SVGs and fixes the "gradient bug".

Results:
+ Total file size reduction 4.1 MB
+ Various icon fixes
+ Fixed the baseplate and shadow opacity bugs of the KDE/Qt issues #2016 
+ Improved SVG readability by converting one-line files to multi-line-layout
+ Fixed the *"gradient bug"* where changes to gradient colours wouldn't be applied

### CODE REVIEW

**Comment by palob** [comment]
Hmm, it says *Files changed 1,811*. Actually as far as I can see all icons in the ``apps`` folder were changed.

**Comment by palob** [comment]
The total number of files in *apps* is 3515.
``find -type l | wc -l`` shows 1703 as the number of links,
``find -type f | wc -l`` shows 1812 as the number of SVG files.

So one missing?

**Comment by dirtydancing** [comment]
Confirmed in Arch/GNOME 3.16 that everything looks fine with the changed Circle icons and that the "gradient bug" is fixed (I modified a couple of gradients including `unsettings.svg`, all fine).

As to the file count: I also get 1812 (not 1811) files and 1703 symlinks in `apps`. Modification dates of the files are all the same, so there seems to be no icon missing (?).

**Comment by palob** [comment]
Ahh, only 1809 SVGs changed +2 ... probably justchanged the modes of the two ``index.theme`` files.

**Comment by dirtydancing** [comment]
If only 1809 SVGs changed, then 3 of 1812 in `apps` did not?

**Comment by palob** [comment]
That's the 3 PNGs :)

**Comment by dirtydancing** [comment]
Ah, OK :)

**Comment by palob** [comment]
Ok, I inadvertendly changed the PNG mode, now one too less?

**Comment by dirtydancing** [comment]
One question: currently, the file permission for the icons are rw-rw-r-- (664), and as proposed here they are rw-r--r--(644).

Is this change intended?

Actually, also currently there are some 644 files, e.g. `liteide.svg` or `luxrender.svg` or `cpuinfo.svg`, but these seem to be just exceptions. Currrently, `web-pushbullet.svg` is even 775.

**Comment by palob** [comment]
As far as I can see most SVG icons have been 644 (``-rw-r--r--``) before my commit and still are.
I've fixed the 755 ones.

**Comment by dirtydancing** [comment]
Well, this might have to do with cloning from GitHub: for some reason, in the directory that I cloned via git, the icons are 664, whereas when I just checked the .zip-download, the same icons were 644. Maybe I just got s.th. wrong on my side.

**Comment by Foggalong** [comment]
Is this fine to be merged then? I'm taking it doesn't fix all the problems brought up in the KDE bug?

**Comment by palob** [comment]
It's fine to be merged :+1: 

It doesn't fix the Qt issues concerning path clipping and those "strange objects".

**Comment by dirtydancing** [comment]
Just to quickly confirm that git indicated that 1809 files were changed, so no file is missing. Furthermore, 5 mode changes from 755 to 644 were indicated, so the file permissions are clarified as well. All good :)

**Pull request merged**
