### PR TITLE
Icons/Symlinks for Metro series

### PR DESCRIPTION
**Pull request by Eleuin**
Original:
metro
Pushed:
metro_numix

### CODE REVIEW

**Comment by palob** [comment]
Symbol needs to be 1px up :)

**Comment by Eleuin** [comment]
well, i just used the Metro: Last Light icon, adding the symlink for the redux version and then recolouring for Metro 2033 (why didn't the original ever get one? why just the sequel?), but if we want to update both, then ill have a look

**Comment by palob** [comment]
Probably because nobody filed an issue for the original one.

**Comment by Eleuin** [comment]
either way, it does seem that the symbols weren't aligned properly, ive gone ahead and fixed that and did some cleaning up

**Pull request merged**
