### PR TITLE
New Audacity icon

### PR DESCRIPTION
**Pull request by dirtydancing**
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/1158. Cf. also conversation over there.

audacity

### CODE REVIEW

**Comment by palob** [comment]
How does it look with less saturated colours and maybe a darker blue on the headphones for better contrast?

**Comment by dirtydancing** [comment]
Good call! A little less saturation (not too much less esp. for the yellow and red, as otherwise the icon will lose its character) and a somewhat darker blue. Easier on the eyes, and it also scales better. This might seem like a nuance, but I think it makes for quite an improvement. Pushed :)

audacity

comparison

**Comment by palob** [comment]
Alright, let's see if it's ready ro go.
In terms of vividness you can counteract reduced saturation with increased lightness to a certain extent sometimes.

**Comment by dirtydancing** [comment]
Corrected alpha channel for yellow, I just noticed that for some reason I must have accidentally changed that  when changing other values. Still the same icon, though :)

audacity

**Pull request merged**
