### PR TITLE
link for wordpress.com desktop app

### PR DESCRIPTION
**Pull request by m-e-h**
https://apps.wordpress.com/desktop/

### CODE REVIEW

**Comment by m-e-h** [comment]
Actually, for some reason this change isn't being picked up on my desktop?
Did I do this incorrectly? The content of the .desktop file are 
```
[Desktop Entry]
Name=WordPress.com
Comment=WordPress.com Desktop Client
Exec=/usr/share/wpcom/wpcom
Icon=wpcom
Type=Application
StartupNotify=true
Categories=Development;
```

**Comment by Foggalong** [comment]
Did you refresh the icon cache? `gtk-update-icon-cache -f Numix-Circle`

**Comment by m-e-h** [comment]
I did not. Just rebooted. I'll try in a bit. Thanks!

**Comment by m-e-h** [comment]
Removed the cache file and all is good with this. :+1:

**Pull request merged**
