### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by palob**
Fixed missing shadows/gradients, alignment issues, deleted unneeded nodes and run ``svgclean`` for recently added icons.

### CODE REVIEW

**Comment by Foggalong** [comment]
I'm getting an invalid file error for guitarrig5

**Comment by palob** [comment]
Where exactly? Inkscape?

**Comment by palob** [comment]
Well, it's got the gradient fix that, same with ``nomacs.svg``.

**Comment by palob** [comment]
All fine now?

**Comment by Foggalong** [comment]
Yeah, all good :) I'm gonna really have to remember to set up SVG cleaner on this new install :P

**Pull request merged**
