### PR TITLE
Icon for Zandronum

### PR DESCRIPTION
**Pull request by Eleuin**
i think this is finally PR ready after a bunch of tweaking the backplate colour

### CODE REVIEW

**Comment by Eleuin** [comment]
@Foggalong any thoughts?
zandronum

**Comment by Foggalong** [comment]
The top and bottom part of the head need aligning to grid :)

**Comment by Eleuin** [comment]
there we go, was just a centering issue, its now properly aligned :>

**Comment by Foggalong** [comment]
:+1:

**Pull request merged**
