### PR TITLE
Gnome chemistry utils pack

### LINKED ISSUE #1093: Icons for Gnome Chemistry Utils
A free software collection of chemistry applications.
http://www.nongnu.org/gchemutils/

**GChemCalc** (chemical calculator)
Icon=gchemcalc
gchemcalc

**GChemTable** (periodic table)
Icon=gchemtable
gchemtable

**GChemPaint** (editor for structural formulas)
Icon=gchempaint
gchempaint

**GChem3D** (3D structures viewer)
Icon=gchem3d
gchem3d

**GCrystal** (crystal structures)
Icon=gcrystal
gcrystal

**GSpectrum** (simple spectrum viewer)
Icon=gspectrum
gspectrum

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/3796110-icons-for-gnome-chemistry-utils?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
Gnome Chemistry Utils, closes #1093

gchem3d gchemcalc gchempaint
gchemtable gcrystal gspectrum

### CODE REVIEW

**Comment by ChuckDaniels87** [comment]
Real atomic symbols with their respective atomic number.

**Comment by bil-elmoussaoui** [comment]
Awesome !!!!

**Comment by palob** [comment]
Clever idea indeed !

**Comment by ChuckDaniels87** [comment]
:+1:

**Pull request merged**
