### PR TITLE
Adds applications-games fixes #2164

### LINKED ISSUE #2164: Cinnamon Menu Consistency Issue
numixgitissue

Issue is illustrated in above image.

I would give an example symlink but there doesn't seem to be a Numix Circle equivalent for that controller icon, I do however know that the name of that icon is "applications-games". This also doesn't seem to be the only "applications-" prefix icon that is missing an icon or symlink either, fixing this would probably prevent further consistency issues.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/17120143-cinnamon-menu-consistency-issue?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by wa4557**
For now until we figured out if we want circular category icons or not I figure it's best to just add a circular icon for `applications-games`

### CODE REVIEW

**Comment by Foggalong** [comment]
You're missing a shadow :)

**Comment by wa4557** [comment]
Added. It was alpha 25 right?

**Comment by palob** [comment]
Yep. A25 or 10% opacity.

**Comment by Foggalong** [comment]
:+1:

**Pull request merged**
