### PR TITLE
Icon for Wyrmsun

### PR DESCRIPTION
**Pull request by palob**
https://andrettin.github.io/

wyrmsum-numix

### CODE REVIEW

**Comment by Foggalong** [comment]
I'm not sure. The icon is really nice (gradient in particular) but the gradients on the symbol (even though they make it more accurate physically) diverge from the guidelines a bit too much.

**Comment by palob** [comment]
That's how it looks flat:
wyrmsum2

**Comment by Foggalong** [comment]
Ach, that looks nowhere near as good. I'll think about this for a bit see if there's something between which works.

**Comment by Foggalong** [comment]
@palob slightly off topic, but do you fancy joining the Numix developer chat on Telegram? It'd be useful for discussing big picture development strategy which up to now has been clogging up GitHub

**Comment by ChuckDaniels87** [comment]
What about flat shadows?

**Comment by palob** [comment]
@Foggalong Yay, thanks for the invitation.

@ChuckDaniels87 Flat colours on the symbol, like this?
wyrmsun0

**Comment by ChuckDaniels87** [comment]
@palob Yeah, really nice. :wink:

**Comment by palob** [comment]
Pushed!

**Pull request merged**
