### PR TITLE
StuntRally fixes

### PR DESCRIPTION
**Pull request by palob**
Milder colours, fixed alignment, contours-->paths, cleanup.
stuntrally
sr-editor

### CODE REVIEW

**Comment by palob** [comment]
Hmm, don't know why the merge conflicts. Maybe revert #1379?

**Comment by Foggalong** [comment]
Merge conflict is because you haven't merged any upstream changes into the stunt rally branch. Not at keyboard right now, but when I will I'll revert. If you get this first though feel free to fix on your end.

**Comment by palob** [comment]
Still confused. I did my fork after #1379 had been merged and the stuntrally branch yields the same diff compared to my master and to the Numix Circle master. So there shouldn't be any conflicting upstream change.

**Comment by Foggalong** [comment]
That's really weird :(

**Comment by palob** [comment]
I could close this and try once again. Maybe I pasted some commands inadvertently polluting the git record.

**Comment by Foggalong** [comment]
I keep getting errors trying to merge this in. I think it's because you've used the same branch name as before but deleted the original one. Can you try a new one called stuntrally-fixes or something?

**Comment by palob** [comment]
Tried before to no avail. But I will open a new PR after rebasing my fork.

**Pull request closed without merging**
