### PR TITLE
TortoiseHG icon

### LINKED ISSUE #1429: Icon for TortoiseHG
I'm missing an icon for TortoiseHG.

Icon=thg_logo
tortoisehg

Thanks for the work you put in this project!

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
TortoiseHG icon, closes #1429

icons

### CODE REVIEW

**Comment by ChuckDaniels87** [comment]
I'm not sure about the background colour, what do you think about it?

**Comment by Foggalong** [comment]
Yeah, it seems a bit too full. does it look better with a more vibrant background or does that clash with the tortoise too much?

**Comment by ChuckDaniels87** [comment]
Better this one?

icons

**Comment by palob** [comment]
Yep, I think it's better.

**Pull request merged**
