### PR TITLE
Icon for Eureka. Fixes #2279

### LINKED ISSUE #2279: Icon for Eureka Doom Editor
Editor for Doom levels
eureka
icon=eureka

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/21876520-icon-for-eureka-doom-editor?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Eleuin**
eureka

### CODE REVIEW

**Comment by Eleuin** [comment]
just for a comparison (showing what it looks like on my sexy desktop)
numix

**Comment by Eleuin** [comment]
i just seriously could never get the orange and blue to mesh well

**Comment by palob** [comment]
Huh, what was wrong with that one (changed colours on the 2nd)?
eureka
eureka2

**Comment by Eleuin** [comment]
i opened the pull request prematurely, and i could never find a design i liked, but yeah, i think that first one is the keeper

**Pull request closed without merging**
