### PR TITLE
Calligra Suite Icons

### LINKED ISSUE #1040: Icons for Calligra Suite [$31]
Calligra Suite, the third free/open source Office Suite besides LibreOffice and Apache OpenOffice.
Part of the KDE Project.
https://www.calligra.org/

Component Icons:

**Calligra Words** (word processing)
Icon=calligrawords

calligrawords

**Calligra Sheets** (spreadsheets/calculation)
Icon=calligrasheets

calligrasheets

**Calligra Stage** (presentations)
Icon=calligrastage

calligrastage

**Calligra Plan** (project management)
Icon=calligraplan

calligraplan

**Calligra Kexi** (database creation)
Icon=calligrakexi

calligrakexi

**Calligra Karbon** (drawing / vector graphics)
Icon=calligrakarbon

calligrakarbon

**Calligra Flow** (flowcharts)
Icon=calligraflow

calligraflow

**Calligra Braindump** (mindmap, sketches)
Icon=braindump

braindump

**Calligra Author** (e-book authoring)
Icon=calligraauthor

calligraauthor

A numix-circle icon for Krita (digital art) already exists.

<bountysource-plugin>
---
There is a **[$31 open bounty](https://www.bountysource.com/issues/3485123-icons-for-calligra-suite?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
Calligra Suite Icons, closes #1040

Suggestions?

__Words:__
calligrawords

__Sheets:__
calligrasheets

__Stage:__
calligrastage

__Plan:__
calligraplan

__Kexi:__
calligrakexi

__Karbon:__
calligrakarbon

__Flow:__
calligraflow

__Braindump:__
braindump

__Author:__
calligraauthor

### CODE REVIEW

**Comment by Foggalong** [comment]
Nice work with the C! Only potential issue that jumps out is the mix of tilted and non-tilted symbols - any reasoning behind the mix? Great job there though :)

**Comment by ChuckDaniels87** [comment]
Just an aesthetic decision, they got very different shapes so I choose what I thought the best option for each one. More feedback, please. :smile:

**Comment by Foggalong** [comment]
For sheets and words keep the hole punches consistent. Either shapes layered on top of then sheet or cuts into the sheet itself. Being icons in the same suitemit would be good to have this the same across both.

**Comment by ChuckDaniels87** [comment]
I was fixing it a bit before you answered. The base is different for Words and Sheets.

What do you think about these?
calligrasheets
calligrawords

**Comment by Foggalong** [comment]
That should be better for keeping things sharp - is everything aligned to grid for those 2? How would flow lookmwith the same treatment?

**Comment by ChuckDaniels87** [comment]
Tomorrow I'll check Sheets, Words should be fully aligned to the grid. I'll post non-rotated Flow too.

**Comment by ChuckDaniels87** [comment]
In my last commit I've tried to snap to the grip all straight lines of Sheets and Words. The problem here is Sheets, lines are quite narrow and cell pretty small compared with the grid but I think it doesn't look bad.

Here an example of Flow non-rotated (it is pushed), I am not sure if I prefer it rotated:
calligraflow

**Comment by Foggalong** [comment]
That's a problem - if you're going to have it non-rotated the lines have to be aligned to grid or it just ends up looking like a mess @ 48px :(
screenshot - 160315 - 12 00 56

Think you might be right about flow, it did look a bit better tilted :)

**Comment by ChuckDaniels87** [comment]
New version:
calligrasheets calligrasheets48

**Comment by Foggalong** [comment]
Looking great :D

**Comment by palob** [comment]
Yep, looking great + distinctive & true to original :+1:

**Comment by ChuckDaniels87** [comment]
I'm glad you like it. :wink:

**Comment by Foggalong** [comment]
Lets merge it in then! All good to go?

**Comment by ChuckDaniels87** [comment]
Sure!! :wink:

**Comment by Foggalong** [comment]
Awesome! :D

**Pull request merged**
