### PR TITLE
Natron Icon

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
Natron Icon, Issue #1542 

icons

### CODE REVIEW

**Comment by ChuckDaniels87** [comment]
Error in the icon push, I'll correct it.

**Comment by ChuckDaniels87** [comment]
Ready

**Comment by palob** [comment]
Just to be sure: Is it on purpose that the outer "N lines" aren't straight vertical?

**Comment by ChuckDaniels87** [comment]
Yep, it is tge purpose. ;)

**Comment by ChuckDaniels87** [comment]
Well, I can change it if it looks bad.

**Comment by palob** [comment]
It doesn't look inherently bad, it's just that straight lines look sharper. But if it scales well, why not.

**Comment by ChuckDaniels87** [comment]
You're right @palob, I've fixed it. :)

**Pull request merged**
