### PR TITLE
Icon for Jasp Desktop

### PR DESCRIPTION
**Pull request by palob**
statistical package
https://jasp-stats.org/

**Original icon:**
Icon0jasp-desktop
jasp-desktop-ori

**Pushed icon:**
jasp-desktop

**Alt (subtle non-drop non-Numixy shadow below the circles):**
jasp-desktop1
jasp-desktop1-2

### CODE REVIEW

**Comment by Foggalong** [comment]
While I do like the drop shadow, breaks the guidelines for Numix so can't merge. Really nice effect though :)

**Comment by palob** [comment]
It's just on the alt :)

**Comment by Foggalong** [comment]
@palob could we possibly add a colourful background? Looks really nice but a little plane as is

**Comment by palob** [comment]
This (not pushed yet)?
jasp-desktop

**Comment by Foggalong** [comment]
Maybe a few shades lighter?

**Comment by palob** [comment]
jasp-desktop
jasp-desktop0b

**Comment by Foggalong** [comment]
Go with the second one :)

**Comment by palob** [comment]
Pushed :+1:

**Pull request merged**
