### PR TITLE
Icon for RawStudio. Fixes #1590

### LINKED ISSUE #1590: Icon for RawStudio
"Rawstudio is an open-source program to read and manipulate RAW images from digital cameras."
http://rawstudio.org/

Icon=rawstudio
rawstudio

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8726746-icon-for-rawstudio?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by palob**
Icon for RawStudio. Fixes #1590
Pushed (updated):
rawstudio0

Alt:
rawstudio-icon
rawstudio2
rawstudio1

### CODE REVIEW

**Comment by Foggalong** [comment]
Really like the 3rd one!

**Comment by palob** [comment]
This one
rawstudio2
or the white one?

**Comment by Foggalong** [comment]
That one :) colours look nice as a 4 part swirl
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by palob** [comment]
Up :+1:

**Comment by ChuckDaniels87** [comment]
Nice one

**Pull request merged**
