### PR TITLE
Icon for QtAV player

### PR DESCRIPTION
**Pull request by palob**
http://wang-bin.github.io/qtav.org/

Original:
qtav-ori

Pushed:
qtav

### CODE REVIEW

**Comment by Foggalong** [comment]
I know it's keeping with the original icon but putting a big fat veto on that centred symbol

**Comment by palob** [comment]
So you'd prefer it centered?

**Comment by Foggalong** [comment]
Yeah, definitely

**Comment by palob** [comment]
Arrow as well?

**Comment by palob** [comment]
qtav

**Pull request merged**
