### PR TITLE
Next round of fixes

### PR DESCRIPTION
**Pull request by palob**
alignment fixes, shadow fixes, transparency fixes, simplified shapes, bigger symbol for ``gcstar.svg``.

### CODE REVIEW

**Comment by wa4557** [comment]
There are a few icons left with a `clipPath` as well (chrome-gcjbnclfkeffmdfdhflnadahgmajfgcm-Default.svg steam_icon_274170.svg ipscan.svg links.svg chrome-gcjbnclfkeffmdfdhflnadahgmajfgcm-Default.svg turpial.svg knetwalk.svg gnome-alsamixer-icon.svg ). Might be a good idea to clean them up as well

**Comment by palob** [comment]
Did you check if that's all left with clipping objects?

**Comment by wa4557** [comment]
Yeah

**Comment by palob** [comment]
Did you check with latest master? I could only find a ``clipPath`` in steam_icon_274170.svg.

**Comment by wa4557** [comment]
https://github.com/numixproject/numix-icon-theme-circle/search?utf8=%E2%9C%93&q=clippath+OR+clip-path

**Comment by palob** [comment]
How strange is that? I can't find any ``clip`` in the ``chrome-....`` icon from my local branch.

The other have got ``style="clip-path:none`` which as far as I can see doesn't come with unwanted effects. Will remove it anyway.

**Comment by palob** [comment]
@Foggalong It's ready to be merged.

**Pull request merged**
