### PR TITLE
Resize for Tresorit

### PR DESCRIPTION
**Pull request by gregorydk**
Resize to 22x26. Fixes https://github.com/numixproject/numix-icon-theme-circle/pull/2284

### CODE REVIEW

**Comment by palob** [comment]
LGTM :+1: 
Yet a merge conflict again.

A tniy hint: In case you want to get rid if the slight greyish outline between the 3 paralelograms, move down the upper parallelogram 2 times and move its bottom node to X24 Y11.

**Comment by gregorydk** [comment]
The greyish outline doesn't bother me, as it looks like a lighting effect. I have no idea about the cause for the conflict though, nor how to resolve it.

**Comment by palob** [comment]
It's because you haven't got the merge/revert of the previous PR in your branch but are doing this PR from the same branch.

Do you have your unchanged master branch on your drive? 

If not clone it again, ``git clone https://github.com/gregorydk/numix-icon-theme-circle`` will clone it to your ``$HOME`` directory.

Go into the newly cloned directory and pull the latest upstream changes
``git pull https://github.com/numixproject/numix-icon-theme-circle``

Get them to your GitHub repo ``git add --all`` ``git push origin master``, no commit.

The cleanest way might be to open a new branch and do a new PR:

Duplicate the cloned folder, copy the latest icon into it, and push it to a new branch, say ``tresorit2``.
``git add --all`` ``git commit -m "commit message"`` ``git push origin master:tresorit2`` and do a new PR.

**Comment by gregorydk** [comment]
I ended up reforking the repo and doing a new PR. Hope everything is okay now.

**Comment by palob** [comment]
Reforking is OK as well :+1:

**Comment by gregorydk** [comment]
Yep.

**Comment by palob** [comment]
But you didn't:)

**Comment by gregorydk** [comment]
Oops :-)

**Pull request closed without merging**
