### PR TITLE
Icon for Trello

### PR DESCRIPTION
**Pull request by onemenzel**

### CODE REVIEW

**Comment by palob** [comment]
LGTM but isn't this what we've already got as [chrome-oflhioojkbelepjlnafgmgkkjhojphcg-Default.svg
](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/chrome-oflhioojkbelepjlnafgmgkkjhojphcg-Default.svg)?

**Comment by onemenzel** [comment]
Yes. you are right ^^' seems like I overlooked that. There should probably be some symlinks added to this.

**Comment by palob** [comment]
Can you transform your new files into symlinks to``chrome-oflhioojkbelepjlnafgmgkkjhojphcg-Default.svg``?

**Comment by onemenzel** [comment]
@palob shall this still be changed now that it got merged?

**Comment by palob** [comment]
@Foggalong did it :)

**Pull request merged**
