### PR TITLE
Cleans up 22x22/status

### LINKED ISSUE #1601: Several (app) status icons are missing in size 24x24
Hi, I am filing this report against Numix-Circle and not against Numix base because of https://github.com/numixproject/numix-icon-theme/issues/190

Now that Xubuntu has a panel canvas size of 24x24 (and e.g. 24x24 is also the wingpanel canvas size in elementary OS Freya, currently in Beta 2), several of the Numix status icons look too big and a little blurred because they only come in size 22x22 and not in 24x24. If they are missing in 24x24 but are present in 22x22, the 22x22 icons have to get scaled to 24x24, and that causes a bit of "friction".

In contrast, the panel canvas size in Ubuntu is 22x22, so all looks fine on Ubuntu.

Examplary comparative screenshot of the panel in Ubuntu 14.10 ("bare metal") above and Xubuntu 14.10 (VM) below (affected status icons pointed to):

xubuntu1410_canvas_24x24

In this screenshot, the affected status icons are Shutter, Redshift, SysPeek and Y PPA Manager.

In Numix-Circle, there is a directory `22x22/status`, but not yet a directory `24x24/status`. So basically, the status icons in `22x22/status` would have to be added to `24x24/status`. Some of these icons in size 24x24 are already present in Numix base and just would have to be copied over to Numix-Circle, others are not.

This should be manageable by taking Numix-Circle's `22x22/status` directory as a guideline, so I filed this collective report. Please let me know if I should file a specific bug report for every specific status icon.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8906314-several-app-status-icons-are-missing-in-size-24x24?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by wa4557**
In order to have a little bit more consistency and before going to fix #1601, I figured it might be a good idea to clean 22x22/status aligne a few icons and make them all the same colour (#dcdcdc).

### CODE REVIEW

**Comment by wa4557** [comment]
@Foggalong : Can you elaborate why there are no "idle" icons in Numix-Circle-light? (just like redshift-status-off etc...)? Shouldn't they change their color too from #dcdcdc to #353535?

**Comment by Foggalong** [comment]
Light icons don't need them I don't think becuase it should be idle to grey rather than white or black.

**Comment by wa4557** [comment]
I see, makes sense. So this is the final commit for this pull request, applies the same fixes also to the light theme, only a few minor changes (a few icons from the "dark" theme were missing, for example evernote)

**Comment by dirtydancing** [comment]
I am not sure about what has been said here about Numix-Circle-Light and the status icons in it. Then again, I am not sure what you mean by "idle" icons. Please cf. e.g. my issue report concerning Redshift https://github.com/numixproject/numix-icon-theme-circle/issues/1286. I would argue that these icons are needed in Numix-Circle-Light.

Numix-Circle-Light does not inherit Numix-Circle, but only Numix-Light. Numix-Light inherits Numix, but regarding the status icons in the panel, Numix-Circle/Numix-Circle-Light are the relevant icon themes.

Just putting this out here for consideration, I might have completely missed the point discussed here :-)

**Comment by wa4557** [comment]
I van confirm that, they are definitifely missing. I could add them instantly. @Foggalong: should I open a new pull request for that or can I and them her? There are actually only a few missing...

**Comment by wa4557** [comment]
closing because there are no more status icons in circle

**Pull request closed without merging**
