### PR TITLE
GUFW icon enhancement

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
GUFW icon enhancement: remove strokes, change colours.

Previous icon got not coherent red strokes:
pre-icon

I've removed the strokes and remodelled the icon changin colours:
icon

I've used those colours cause they appear in the main menu:
uf

### CODE REVIEW

**Comment by dirtydancing** [comment]
Good idea! I have noticed as well that the canvas colour of this icon is not ideal in the system settings.

I am not sure about the light blue though, because there are already a couple of blue canvas icons in the system settings. This might be an opportunity to choose another icon canvas colour (?).

Screenshot from Ubuntu 14.10 (icon circle shape is even less visible with Ambiance GTK theme, which has a slightly lighter background colour):

systemeinstellungen

**Comment by ChuckDaniels87** [comment]
Good call, how about this one?
icon

**Comment by dirtydancing** [comment]
I like the vibrancy of the new one. To me, it seems that a yellow colour might be suitable here. So I took your icon into Inkscape and just turned the colour wheel to yellow (#f5f559). What do you think?

Screenshot:
gufw_yellow

**Comment by Foggalong** [comment]
I think I prefer the orange :)

**Comment by ChuckDaniels87** [comment]
In my experience, vibrant yellow backgrounds are tricky and constrast is not good. White and yellow usually got bad result put together and when you scale it just got worse.

**Comment by dirtydancing** [comment]
Thanks for your feedback, I see. Nice improvement on the current icon! :-)

**Comment by ChuckDaniels87** [comment]
Thank you! :+1:

**Comment by costales** [comment]
I'm here again! I didn't think in this property for Gufw :$
I'd like that Gufw will have custom icon, but it's not working what I'm trying:

I have the icons:
`costales@desktop:~/Desktop/gui-ufw$ find /usr/share/icons -name "gufw*.svg"`
`/usr/share/icons/Numix-Circle/48x48/apps/gufw_menu.svg`
`/usr/share/icons/Numix-Circle/48x48/apps/gufw.svg`
`costales@desktop:~/Desktop/gui-ufw$`

And I tried changing the property for a dynamic path:
`costales@desktop:~/Desktop/gui-ufw$ grep '"icon"' /usr/share/gufw/ui/about.ui`
`    <property name="icon">gufw</property>`
`costales@desktop:~/Desktop/gui-ufw$ `

But the icon in the about dialog is none. Any idea, please?

@ChuckDaniels87 You did an awesome work! I really like it a lot!! Thanks!!

**Comment by dirtydancing** [comment]
@costales Are you referring to the blue Gufw icon marked in the center of the screenshot below? That is the about dialogue. And is that blue icon still the default Gufw icon? 

@ChuckDaniels87 Shoot, we might have got the icon colours themselves inaccurate then :), because they apparently are still blue for the general Gufw icon? The green and red only show when the status is turned on. In contrast, when turned off, the icon colours become grey as in the screenshot below.

On a further note: would it be possible/recommendable to make the symbol a bit bigger in relation to the canvas size? To me, it looks a little small, esp. when compared to the other symbols in the system settings window. What do you make of all this?

gufw

**Comment by costales** [comment]
I was talking about the icon in launcher and the about window :) they
persist as the default icon.
I'd like a themeable Gufw in a complete way :)

And I like the current shield. It's not a problem for me that the shield
has another colors.

A hug!

On Monday, March 30, 2015, dirtydancing <notifications@github.com> wrote:
> @costales Are you referring to the blue Gufw icon marked in the center of
the screenshot below? That is the about dialogue. And is that blue icon
still the default Gufw icon?
>
> @ChuckDaniels87 Shoot, we might have got the icon colours themselves
inaccurate then :), because they apparently are still blue for the general
Gufw icon? The green and red only show when the status is turned on. In
contrast, when turned off, the icon colours become grey as in the
screenshot below.
>
> On a further note: would it be possible/recommendable to make the symbol
a bit bigger in relation to the canvas size? To me, it looks a little
small, esp. when compared to the other symbols in the system settings
window. What do you make of all this?
>
> <
https://ci6.googleusercontent.com/proxy/MfnyJ69Cga-qleEYOVT1BuqnKuFMroEfjmhzk08Rc9pUL5p1xjfcdbNpdZvbzlFnaiYmvec-bp-akK9PqjXa0P5Nz-CN1bIjo3XNnAl5poDCk_BSrMALqRksD2mWqTdJvq_niOkUXQBNpKQYYPUEHM8IKR76kFDfkQ=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/7164227/6906855/9da2d230-d731-11e4-8485-837e3296cc62.png
>
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/EOhHBbxW9mqvyhBdyXiWW6HIxuwbpx5CrkxH-KNtBAjkngg027U8bjlSvOZ4NvsQX-m5luYpmjtFNi2pPwSIDmhI0kbxggK70gluSGd-XAbVzONmq3yO6Yph9dgq8zqQcwjdgUbuk_QbkKehJ_d0KJcpQwbwfA=s0-d-e1-ft#https://github.com/notifications/beacon/AFnTQmbU2iG0iae6h7y-CWQUr4BxuAMjks5n6bOOgaJpZM4D2_To.gif
>

**Comment by dirtydancing** [comment]
Ah, good! I really like the shield colours as well in the new Numix-Circle Gufw icon design :-)

As to the launcher: In Ubuntu 14.10, the Unity launcher is displaying the Numix-Circle icon. Maybe you are referring to s.th. else? (if you look closely, in the Ubuntu desktop screenshot above, you can see the Numix-Circle icon stacked in there, about 5th from the bottom) :)

**Comment by ChuckDaniels87** [comment]
@dirtydancing I thought that those colours fit better in Numix despite not being the same of the original icon. Anyways, they appear in the main window of the software and look good :yum:. I followed guidelines for the symbol size, if @Foggalong gives me permission I could do it bigger.

**Comment by ChuckDaniels87** [comment]
Ops, we commented at the same time @dirtydancing.

**Comment by dirtydancing** [comment]
Yep, agreed that the colours fit better in Numix, and they do appear in Gufw when turned "on", and turning Gufw "on" is arguably the entire point of installing Gufw in the first place :-)

**Comment by ChuckDaniels87** [comment]
About symbol size, it is strange that some icons in the configuration panels looks much bigger than 26x26px or even 30x30.

**Comment by palob** [comment]
I think the green/red colouring refelcts nicely the let pass/block characteristics of a firewall :)

**Pull request merged**
