### PR TITLE
Icon for franz

### PR DESCRIPTION
**Pull request by kinetoskombi**
Hello, I'm new here and want to contribute to this amazing project. I'm currently using Franz, another amazing project that combines a lot of messaging applications on a beatiful uniform interface. So, I've tried to make an icon based on the official one and other icons of the Numix project.

http://meetfranz.com/

original icon
franz

my proposal
franz

### CODE REVIEW

**Comment by palob** [comment]
That's a nice design but the symbol is a bit big. Can you give it a shot at 26px symbol width?

Morevover there's some strange unused stuff in the SVG code. You can get rid of that using Inkscape's ``vacuum-defs`` function (cleaning entry in the ``File`` menu).
For some reason when opening your icon in Inkscape the pixel grid is set to invisible in the document options.

**Comment by kinetoskombi** [comment]
Nica, I'll try to fiz it. Thank you for the feedback!

**Comment by palob** [comment]
Jep, that's it. Can you give it a shot with a slightly blue-tinted background?

Please make sure to open the SVG with a text editor and delete the
```
<!-- Created with Inkscape (http://www.inkscape.org/) -->
```
line in the SVG code. For whatever reason some applications can't get over it.

**Comment by kinetoskombi** [comment]
Resolves #2963

**Comment by Lazza** [comment]
I would suggest to keep the original colors, like this (based on @kinetoskombi's work): [franz.svg.txt](https://github.com/numixproject/numix-icon-theme-circle/files/391960/franz.svg.txt)

franz

**Comment by Foggalong** [comment]
@Lazza It's truer to the original, but it's also a bit boring. I don't personally use the app though while you two do, so if you'd prefer the original colours (hopefully after giving this one a go first) then feel free to open an enhancement request or a pull request and we'll make the change :)

**Pull request merged**
