### PR TITLE
Icon for Jmol

### LINKED ISSUE #2498: Icon for Jmol
Missing icon for Jmol (an open-source Java viewer for chemical structures in 3D).
[Link to Project homepage](http://jmol.sourceforge.net/). [Link to Ubuntu package](https://launchpad.net/ubuntu/+source/jmol).

Name=Jmol
Comment=Molecular Viewer
Icon=jmol-icon

jmol_icon_128

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26111362-icon-for-jmol?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by palob**
Fixes #2498 

jmol-icon

### CODE REVIEW

**Comment by Foggalong** [comment]
I think that needs moving 1px to the right to offset the triangle illusion

**Comment by palob** [comment]
jmol-icon
:+1:

**Comment by Foggalong** [comment]
\O/

**Comment by ChuckDaniels87** [comment]
I like this one. :wink:

**Pull request merged**
