### PR TITLE
Added a tray icon for nvidia

### PR DESCRIPTION
**Pull request by alfredvaa**
nvidia
I added a grey version of the nvidia icon to match the other grey icons in Unity tray (upper right corner).

### CODE REVIEW

**Comment by alfredvaa** [comment]
nvidia
Changed color to this instead.

**Comment by Foggalong** [comment]
For status icons we don't stick to the circle design, so it would just be the Nvidia logo. Take a look at the SVGs of our other icons for the colours needed :)

**Comment by alfredvaa** [comment]
nvidia
I see! I have updated it now!

**Comment by Foggalong** [comment]
Almost spot on, just need to add the undershadow as shown here
screenshot - 080215 - 20 44 39

**Comment by alfredvaa** [comment]
That should be it!

**Pull request merged**
