### PR TITLE
Icon for Wolfenstein games

### LINKED ISSUE #2175: Icon for Return To Castle Wolfenstein
FPS from id Software
return_to_castle_wolfenstein
icon = rtcw

### PR DESCRIPTION
**Pull request by Eleuin**
Did up an icon for some of the wolfenstein games. any issues, and ill get on a fix for it

### CODE REVIEW

**Comment by palob** [comment]
A few issues: 
+ The baseplate colour is too saturated and lacks a gradient (10L brighter at the top)
+ Several vertical/horizontal lines arent't aligned to the pixel grid
+ The shadow has a wrong colour

**Comment by Foggalong** [comment]
@Eleuin We actually have a Wolfenstein: ET icon knocking about somewhere so there's no need to make symbol, just reuse the elements from there but with colours relevant to the newer games.

**Comment by Eleuin** [comment]
@foggalong thats pretty much what i did for the most part
@palob noted for any future icons, ill hop on a fix for those later today :D

**Comment by palob** [comment]
Some more guidance for future icons:
+ Numix Circle [guidelines](https://github.com/numixproject/numix-wiki/wiki/Guidelines)
+ A [thread](https://github.com/numixproject/numix-icon-theme-circle/issues/1277) with discussion
 You can find more design discussions in other PR conversations.

**Comment by Eleuin** [comment]
thanks, i'll make sure to bookmark it for future icons.

**Comment by Eleuin** [comment]
icons should now be up to spec

**Comment by palob** [comment]
Are both icons the same on purpose? If so you can realise one as symbolic link to the other instead of a full copy.

**Comment by Eleuin** [comment]
checked in, they are different
rtcw
wolfenstein

**Comment by Foggalong** [comment]
@Eleuin symbols are fine now, the gradients just need fixing. The colours need to be the same in every way, except the top one has to be 10 **L**ighter than the bottom one.

**Comment by Eleuin** [comment]
Its a learning process. I do appreciate all the feedback and will remember this for the future. I'll get on the gradients

**Comment by Foggalong** [comment]
Not a problem! :)

**Comment by Eleuin** [comment]
updated the background gradient :D

**Comment by Foggalong** [comment]
Gradient still not quite right. Check out the numbers in the HSL panel. The values for S should be the same in both the top colour and the bottom colour. The L values aren't 10 apart in the black icon either :)
screenshot_2015-05-28_15-33-22
screenshot_2015-05-28_15-33-06

**Comment by Eleuin** [comment]
there, that should be better. i think i get it now :P

**Comment by Foggalong** [comment]
You got it! :D

**Pull request merged**
