### PR TITLE
Distinct icon for Sky Chart

### PR DESCRIPTION
**Pull request by palob**
I've had this resting on my disk for a while:
Diverging from the guidelines but recognisable and small sizes and true to the original icon:
skychart

Alt with shadows:
skychart-shadow

Maybe a bigger meteor?

### CODE REVIEW

**Comment by ChuckDaniels87** [comment]
It diverges from guidelines but it is really nice icon. Could you try bigger meteor?

**Comment by Foggalong** [comment]
While I think it's a nice icon, I'm not going to merge it because it's too far from the guidelines.

**Comment by palob** [comment]
That's actually a good idea, will try it.

**Comment by palob** [comment]
So something like this?
skychart2

**Comment by Foggalong** [comment]
Yeah, that's much better :)

**Comment by palob** [comment]
Pushed it :+1:

**Pull request merged**
