### PR TITLE
Icon for Abrowser. Fixes #1457

### LINKED ISSUE #1457: Icon for Abrowser
Trisquel's deafuelt browser (modified Firefox)

Icon=abrowser -- located in /usr/share/pixmaps
abrowser.desktop
mozicon128

### PR DESCRIPTION
**Pull request by palob**
Icon for Abrowser, issue #1457
abrowser

### CODE REVIEW

**Comment by palob** [comment]
Maybe better without the "A"?
abrowser2

**Comment by Foggalong** [comment]
I like the idea of having the A there, but not sure if the original one is too brighrt

**Comment by palob** [comment]
Maybe this colour scheme?
abrowser3

**Comment by Foggalong** [comment]
Better, but not quite enough contrast between the countries and A. Maybe a darker A?

**Comment by palob** [comment]
abrowser2

**Comment by Foggalong** [comment]
That's the one! Push and I'll merge :)

**Comment by palob** [comment]
Done. :+1:

**Pull request merged**
