### PR TITLE
add Allcast Receiver Chrome app icon

### PR DESCRIPTION
**Pull request by m-e-h**
A smaller inner-circle made it look too much like a record so I made it square. I think it's supposed to resemble a television..
Let me know if the size ratios are ok.
Thanks!

### CODE REVIEW

**Comment by Foggalong** [comment]
Yeah, that's fine :)

**Comment by ChuckDaniels87** [comment]
It would be nice to have icon preview in the pull request. (use PNG or something)

**Comment by ChuckDaniels87** [comment]
BTW @m-e-h , nice job with the icon.

**Comment by m-e-h** [comment]
Thanks @ChuckDaniels87! 
I can do a png next time. But github will show the svg on the pr link https://github.com/m-e-h/numix-icon-theme-circle/blob/41783d9b6cf6ffb7b37bd7af8d716f53b0591068/Numix-Circle/48x48/apps/chrome-hjbljnpdahefgnopeohlaeohgkiidnoe-Default.svg

**Comment by ChuckDaniels87** [comment]
Sometimes there are problems with the SVG preview and it is a lot of faster to check it at one glance at the pull request. :smiley:

**Pull request merged**
