### PR TITLE
Icon for Rocket.Chat

### PR DESCRIPTION
**Pull request by palob**
https://github.com/RocketChat/Rocket.Chat
rocketchat

### CODE REVIEW

**Comment by Foggalong** [comment]
Can we try a blue like the one from the logo for the baseplate? :)

**Comment by palob** [comment]
rocketchat1
rocketchat1b

Or maybe a lighter blue?

**Comment by palob** [comment]
Or maybe a lighter blue?
rocketchat2
rocketchat3

**Comment by Foggalong** [comment]
I really like dark blue #2 :)

**Comment by palob** [comment]
Pushed
rocketchat1b

**Comment by Foggalong** [comment]
:+1:

**Pull request merged**
