### PR TITLE
Europa Universalis IV icon

### LINKED ISSUE #1665: Icon for Europa Universalis IV (Steam)
Game: __Europa Universalis IV__
AppID: __236850__

steam_icon_236850

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9321720-icon-for-europa-universalis-iv-steam?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
Europa Universalis IV, closes #1665

icons

### CODE REVIEW

**Comment by Foggalong** [comment]
Commendable for sticking to while simultaneously improving upon the original design, but a bit too far from the guidelines to merge in. Any chance we can see what the compass would look like as a 30px symbol?

**Comment by ChuckDaniels87** [comment]
Here some alternative designs:
1-
icons

2-
icons

3-
icons

**Comment by Foggalong** [comment]
We're going with 3 :)

**Comment by ChuckDaniels87** [comment]
Ready. :wink:

**Comment by palob** [comment]
:+1: 
Are the dark "needles" below the broght ones connected? Looks a bit like there was an outline.

**Pull request merged**
