### PR TITLE
Icon for Encryptr

### PR DESCRIPTION
**Pull request by gregorydk**
Icon for Encryptr. https://encryptr.org/

It is hard-coded!
Icon=/usr/share/pixmaps/Encryptr.png

### CODE REVIEW

**Comment by palob** [comment]
Hi, @gregorydk at the moment it is better to wait until #2606 is merged before submitting more PRs.

Otherwise you or @wa4557 will need to resolve merge conflicts.

**Comment by wa4557** [comment]
Actually for circle it is not so bad, so although it would be cool to keep new PR to a minimum I think it's ok to be merged :)

**Comment by palob** [comment]
@gregorydk What's the ``.desktop`` file name? It's needed for the hardcode-fixer.

In case you didn't know in case of circular symbols you can go up to 30px x 30px.

**Comment by ChuckDaniels87** [comment]
Just  a suggestion about the icon baseplate: what about a _brighter_ color? With gradient L:170-160 (HSL), for example. This will make icon fit better with Numix style ([vivid colours](https://github.com/numixproject/numix-wiki/wiki/Guidelines#colouring)).

**Comment by gregorydk** [comment]
@palob encryptr.desktop

**Comment by palob** [comment]
@gregorydk Thanks, [added a fix](https://github.com/Foggalong/hardcode-fixer/pull/187) for a Numix Circle icon ``Encrytr.svg``

**Comment by Foggalong** [comment]
Inkscape gradient bug has taken hold here :(

**Comment by palob** [comment]
@gregorydk Looks like forgot the option to prevent it in your SVGclean script.

**Pull request closed without merging**
