### PR TITLE
Translator icon - colourful bubbles

### PR DESCRIPTION
**Pull request by palob**
Now in colourful colours :rainbow:

translator-new

See #1496 for the old one.

### CODE REVIEW

**Comment by Foggalong** [comment]
Check your pull, can't be automerged because of clashes

**Comment by palob** [comment]
Yeah, that's since my base fork is without the old icon.

**Comment by palob** [comment]
You could revert #1496, this should make automerge possible.

**Comment by Foggalong** [comment]
I wasn't sure about the colours on this so asked Numix folk. Consensus is that the colours are fine, just the purple needs to be a bit less dominant

**Comment by palob** [comment]
Like this?
translator

**Comment by ChuckDaniels87** [comment]
Really nice ;)

**Comment by Foggalong** [comment]
Yeah, that's the one. Push it and I'll sort out the merging

**Comment by palob** [comment]
Pushed :+1:

**Pull request merged**
