### PR TITLE
Adds foxit reader icon

### LINKED ISSUE #2581: Icon for FoxitReader
foxitreader-64x64
Finally one of the best (though proprietary) pdf viewers was ported to Linux. 
http://www.webupd8.org/2015/09/foxit-pdf-reader-sees-new-linux-release.html
Icon line says:
`Icon=/home/root/.local/share/icons/hicolor/64x64/apps/FoxitReader.png`

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27084129-icon-for-foxitreader?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by wa4557**
Icon for foxit pdf reader. Fixes #2581

### CODE REVIEW

**Comment by palob** [comment]
I think it looks a bit Firefoxy with that colours.

**Comment by wa4557** [comment]
Yeah true. The orange is however the "offical" foxit colour. Something different than the blue? Green maybe?

**Comment by palob** [comment]
Or the original orange-white combination? Is it too bland?

**Comment by wa4557** [comment]
Some kind of bluish white seems to be just fine
unbenannt

**Comment by palob** [comment]
Less Firefoxy :+1:

**Pull request merged**
