### PR TITLE
Added fontmatrix.svg

### PR DESCRIPTION
**Pull request by dirtydancing**
Fixes https://github.com/numixproject/numix-icon-theme-circle/issues/2355.

fontmatrix

### CODE REVIEW

**Comment by palob** [comment]
Cool idea but quite a heavy one. Is it any discernible at sizes below 48px?

**Comment by dirtydancing** [comment]
Yeah, I checked the smaller sizes as well. Of course, the individual "a" letters of the "matrix" are not discernible anymore, but the shape/writing is (f/m, according to the original icon). It just turns into a sort of solid line once the size gets small enough :)

To illustrate, here is a screenshot with Arch/GNOME, larger size in the app overview, smaller size in the dash:

fontmatrix-screenshot

**Comment by palob** [comment]
Maybe a lighter red to have the black part stand out a little more at small sizes?

**Comment by dirtydancing** [comment]
Maybe. I checked a couple of different variants, and the problem with a lighter red was that then the contrast esp. to the right part of the "writing" was suffering. Anyways, I am surely happy to have another look at it :), might just be a little while.

**Comment by palob** [comment]
The white is a bit harsh. It's L254 :)

**Comment by dirtydancing** [comment]
Thanks @palob! Oops, I thought I had gone for Numix white #f9f9f9 :)

**Comment by dirtydancing** [comment]
Lighter version: I checked a couple of variants with the starting point of the colours from above, and I was not really convinced by any. So this version is indeed "lighter" :) White is now Numix white #f9f9f9, and with the modifications suggested by @palob the icon size has now come down from 22 kb to 7 kb.

lighter-version

**Pull request merged**
