### PR TITLE
Enhanced icon for Fotowall

### PR DESCRIPTION
**Pull request by palob**
Made a new icon for Fotowall:
fotowall
Replaces (also used by Fotoxx):
fotowall-before

New icon for digiKam:
digikam
Replaces (also used by screenshot/camera apps):
digikam_alt

### CODE REVIEW

**Comment by palob** [comment]
Btw, issue #992 can be closed.

**Comment by Foggalong** [comment]
Can you put the FotoWall icon on the same background as Foto, gives it some unity across the apps.

Put the digiKam one in a separate pull, it's probable that we're going to debate around with that one a bit as it might turn out that both icon types (camera and screenshot) need changing

**Comment by palob** [comment]
Restored digikam.svg as symlink to accessories-camera.svg.

Updated Fotowall icon:
fotowall2

**Comment by Foggalong** [comment]
Thanks :D

**Pull request merged**
