### PR TITLE
Adds dynamic calendar icons

### PR DESCRIPTION
**Pull request by wa4557**
I made dynamic calendar icons (#2019) and also a script that changes it. I have no idea how I should contribute that (a new repo?) anyway here's how to use it: 
you have to do 3 things

-Wait until PR is merged :)

-Copy that script and place it somewhere + make it executable (`chmod +x calendar-script`)
EDIT: With my PR in base [#489] (https://github.com/numixproject/numix-icon-theme/pull/489) I changed the script accordingly:
```
#!/bin/bash
    
function gerror() { sleep 5; exit 1; }
    

day=`date +'%d'`

cuser="${SUDO_USER:-$USER}"
circle=true
if [ -d /home/"$cuser"/.local/share/icons/Numix-Circle/ ]; then
    dir=/home/"$cuser"/.local/share/icons/Numix-Circle/48x48/apps
elif [ -d /home/"$cuser"/.icons/Numix-Circle/ ]; then
    dir=/home/"$cuser"/.icons/Numix-Circle/48x48/apps
elif [ -d /usr/share/icons/Numix-Circle/ ]; then
     dir=/usr/share/icons/Numix-Circle/48x48/apps
else
    circle=false
fi

base=true
if [ -d /home/"$cuser"/.local/share/icons/Numix/ ]; then
    dir2=/home/"$cuser"/.local/share/icons/Numix
elif [ -d /home/"$cuser"/.icons/Numix/ ]; then
    dir2=/home/"$cuser"/.icons/Numix/
elif [ -d /usr/share/icons/Numix/ ]; then
     dir2=/usr/share/icons/Numix/
else
    base=false
fi

if $circle; then 
    cd $dir
    ln -sf calendar-blue-$day.svg google-calendar.svg
    ln -sf calendar-red-$day.svg office-calendar.svg
fi

if $base; then 
    cd $dir2
    places=`find . -name "places" -type d`
    for place in $places
        do
            cd $dir2$place
            ln -sf calendar-$day.svg calendar.svg
        done
fi
```

- Install anachron (most probably already installed) and symlink the script to /etc/cron.daily

### CODE REVIEW

**Comment by wa4557** [comment]
I created a pull request in base additional calendar icons, therefore I remove `calendar.svg` from circle

**Comment by Foggalong** [comment]
If we're doing this it'd have to be as an addon to the Numix Circle theme rather than contained within it. For that reason I've made a [specific repo for the job](https://github.com/numixproject/numix-calendar-icons) :)

**Comment by wa4557** [comment]
@Foggalong does this mean that all the icons will and should be moved to that repo as well, or are those icons staying in the base and circle icon theme? They don't do any harm imo

**Comment by bil-elmoussaoui** [comment]
@wa4557 good job ! 
It would be very cool if the script detect the default calendar application and change it's icons? 
For ex, in Freya i can use the default calendar as i can install an other one..

**Comment by Foggalong** [comment]
@bil-elmoussaoui It doesn't matter which calendar app is being used, it'll make the change for all of them. The symlink for the individual calendar apps points to `calendar.svg` which in turn points to the icon for todays date :)

**Comment by wa4557** [comment]
@bil-elmoussaoui Doesn't matter it changes the calendar icon instead of the desktop files, so safe here

**Comment by Foggalong** [comment]
@wa4557 as you say, no reason the icons can't stay here (and in Base!). Just submit the script and installation instructions the the new repo and all will be good! :)

**Pull request merged**
