### PR TITLE
Icon for mp3splt-gtk

### LINKED ISSUE #3260: Icon for mp3splt-gtk
Missing icon for mp3splt-gtk from the mp3splt project (utility to split audio files without decoding).
[Link to Project Home](http://mp3splt.sourceforge.net/mp3splt_page/home.php). [Link to Project SourceForge](https://sourceforge.net/projects/mp3splt/).

```
Name=Mp3splt-gtk audio splitter
Icon=/usr/share/pixmaps/mp3splt-gtk_ico.svg
```

This icon is **hardcoded**. I have [opened an issue upstream](https://sourceforge.net/p/mp3splt/bugs/202/) to hopefully fix this, targetting the icon line `Icon=mp3splt-gtk`.

### PR DESCRIPTION
**Pull request by palob**
Fixes #3260

mp3splt-gtk_ico0

### CODE REVIEW

**Comment by palob** [comment]
Is this alright?

**Comment by Foggalong** [comment]
I'd like to get the colours of the original icon in there just to keep it recognisable :)

**Comment by palob** [comment]
So orange on black?

**Comment by Foggalong** [comment]
I've just realised that we've both seen very different interpretations of the icon - I saw the whole black circle as a vinyl with the orange being the coloured centre, and the blue as the background :P

**Comment by palob** [comment]
How about this?
mp3splt-gtk_ico

**Comment by Foggalong** [comment]
I'd happily merge that :)

**Comment by palob** [comment]
Pushed, along with a cleanup for ``terminator.svg``.

**Pull request merged**
