### PR TITLE
Fixes #1038

### LINKED ISSUE #1038: Icon for SoftPerfect WiFi Guard
Hey, guys.

Please, create an icon for the following application:

App: SoftPerfect WiFi Guard
Icon=wifiguard.png

guard

Thanks for your attention.

brunces

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/3479754-icon-for-softperfect-wifi-guard?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by hlechner**
#1038

### CODE REVIEW

**Comment by palob** [comment]
Some issues:
The shadow is too dark (try 25A), the baseplate is missing the gradient and the number of nodes on the eyes is quite high + eyes aren't perfectly aligned to the grid.
Overall the icon might be a bit darkish.

**Comment by hlechner** [comment]
I've just converted it from png, re-sized and add the **Fill Bounded Areas** on eyes with pure white.

Based on your comment I changed
- the shadow to 25
- the white from pure white to #f1f1f1
- the black as changed to pure black

I'll try to align it to grid.

But unfortunately I'm not sure how can I solve this issues:
- the baseplate is missing the gradient
- the eyes/nose path is cut out from the black body part unnecessarily.

or maybe I just give up with this and let it for real designers and not me :P

**Comment by palob** [comment]
+the baseplate is missing the gradient
When choosing a colour there is an option for a linear gradient. By default it is placed from left to right.
Place the gradient nodes at (1,1) and (1,47) so as to have a vertical linear gradient.
The colour on the upper node has to be +10L of the colour at the baseplate bottom.

+ the eyes/nose path is cut out from the black body part unnecessarily
Click on the ol body with the node tool. When the nodes show up delete the nodes outlining the eyes.

**Comment by Foggalong** [comment]
Gonna merge this in and apply the fixes :)

**Pull request merged**
