### PR TITLE
Icon for GNUjump. Fixes #1415

### LINKED ISSUE #1415: Icon request for gnujump/xjump
The greatest game of them all. Lovin' those sound effects :laughing: 

Icon=gnujump
gnujump

xjump is the older classical version of the game and it has exactly the same icon but it's a xpm file instead
Icon=xjump-icon.xpm

### PR DESCRIPTION
**Pull request by palob**
Icon for GNUjump, issue #1415 
Pushed:
gnujump

Option:
gnujump4

### CODE REVIEW

**Comment by palob** [comment]
Added a symlink for xjump, *xjump-icon.svg*

**Comment by Foggalong** [comment]
Can we have the alt one - looks a bit better with those colours :)

**Comment by palob** [comment]
Alright, the one with contours is up!

**Comment by Foggalong** [comment]
Thanks!

**Pull request merged**
