### PR TITLE
Icon for Borderlands: The Pre-Sequel

### PR DESCRIPTION
**Pull request by Eleuin**
We can knock this off the list of game icon related issues

### CODE REVIEW

**Comment by Foggalong** [comment]
Try a slightly less harsh blue - somewhere around `5050c3ff` seems good :)

**Comment by Eleuin** [comment]
yeah, a  blue thats 10L-20L does a lot better job at not hurting the eyes :D

**Comment by palob** [comment]
Btw, is it just me or is the Github preview generally broken now?

**Comment by Foggalong** [comment]
@palob Yeah it's broken whenever I see it now, unless it's an icon by @wa4557 for some reason

**Comment by Eleuin** [comment]
@palob i have noticed that the github preview has broken in Firefox, webkit based browsers seem to render them fine though

**Comment by wa4557** [comment]
I use chromium, it might be that

**Comment by Foggalong** [comment]
I meant that commits from @wa4557 always seem to work. When I go to see an icon you've made, even though I'm looking at it in Firefox, it works but no one elses do :P

**Comment by Eleuin** [comment]
i think @wa4557 might be a witch...

**Comment by Foggalong** [comment]
@Eleuin You can go if duller on the blue. Circle is a vibrant theme, but it's a careful line not to fall into harsh

**Comment by wa4557** [comment]
@Foggalong  It seems that I really have mastered github now :P

**Comment by Eleuin** [comment]
@wa4557 nah bud, its obviously the witches

**Comment by Eleuin** [comment]
also, there we go. a bunch lighter

**Comment by Foggalong** [comment]
I've just looked at your original comment in the original issue - what happened to that blue? Looks perfect!

**Comment by Eleuin** [comment]
@Foggalong oh, that blue. I had to redo the icon because i had a mobo issue on my last machine, and i lost the icon. I have since had to redo that, but i can probably go find the shade of blue i used for that :P

**Comment by palob** [comment]
Just open the png in Inkscape and use the colour picker :)

**Comment by Foggalong** [comment]
@Eleuin Oh shit, that's not good! Is it okay? :(

**Comment by Eleuin** [comment]
@Foggalong the new machine that i was previously working on? no, it actually won't even power on, however, i got a 5 year old machine that runs Ubuntu GNOME flawlessly. I can try to recover some of the work that i did previously from their issue threads, however, the original svg's i did are forever lost

**Comment by Eleuin** [comment]
Anyways, i stole the blue from that thread

**Comment by Foggalong** [comment]
Perfect <3

**Pull request merged**
