### PR TITLE
Icon for LTSpice

### PR DESCRIPTION
**Pull request by Jacajack**
I recently created icon for LTSpice, a electronics simulation software.
It doesn't run on Linux, but You can easily use it in WINE, so I thought You may want to consider adding its icon to the set.

This is my Icon:
selection_527

*(Again, sorry for that brown backround)*

I tried to follow guideline, but if something's wrong, let me know, I'm willing to fix it. ;)

### CODE REVIEW

**Comment by palob** [comment]
While this one might be a case for an exception to the rule the symbol is to big currently.
I think a size 30x14 works well. If centered it'll also be aligned to the pixel grid then.

Can you use a slightly lighter and less saturated colour on the symbol and a light reddish vertical gradient for the baseplate (10L lighter on top)?

**Comment by Jacajack** [comment]
Is that better now?
selection_538

**Comment by palob** [comment]
Yep :+1: Maybe a bit more red for the baseplate?

**Comment by Jacajack** [comment]
I saturated gradient a little bit more, this is result:
selection_540

For me it looks fine :)

**Comment by palob** [comment]
Aye, you're getting there.
Alignment is still a bit off + gradient must be from Y position 1 to 47 and 10L lighter at the top.
Btw, in case you don't know you can toggle the pixel grid with the ``#`` in Inkscape.

work

The size of the both red paths (you can merge those if you mant) only needs to be 30x14.
Then duplicate that path, move it 1px down and 1px to the right, colour it black with 10% opacity to have the shadow correctly sized and aligned to the pixel grid.

**Comment by Jacajack** [comment]
Well, I aligned only the bottom part. Should I rescale icon to align both, top and bottom?

**Comment by palob** [comment]
Yes, all horizontal and vertical lines have to be aligned to the pixel grid. Otherwise those lines appear blurry.

**Comment by Jacajack** [comment]
Ok, I'm working on it now, sorry for bothering You :P

**Comment by palob** [comment]
No problem at all, always good to see new contributors :)

**Comment by Jacajack** [comment]
I rescaled symbol to match the grid and set correct gradient end-points.
Visually icon stayed almost the same:
image

**Comment by palob** [comment]
It's correctly aligned :+1:  Size 28x13 now. Maybe that looks even better. Let's see what's @Foggalong's view

**Comment by Foggalong** [comment]
@Jacajack I like the icon, but the gradient is still messed up. It should be only the L (in HSL) value that changes by a value of 10, everything else should remain constant. The gradient nodes should also be aligned to grid and go all the way from the top of the base plate to the bottom in the center.

**Comment by Jacajack** [comment]
@Foggalong Sure, I'll fix that. :)
The weird thing is, that Inkscape won't let me change only L value in gradients, and changes S from 58 to 56 itself, it's pretty annoying. Anyways, I'll try to sort everything out today's evening.

By the way, I think my gradient goes from the bottom of the baseplate to the top, doesn't it?

**Comment by Foggalong** [comment]
Not at the moment no
screenshot_2016-04-21_22-07-20

**Comment by Jacajack** [comment]
That's weird, I can see gradient is at the left side of the icon, and it has proper length 0_0

I will just use new baseplate (unfortunately tomorrow, I had less time than I expected today (sorry!)). And I still have problem with HSL on two different PC's and after updating Inkscape, even when changing other icons' backgrounds.

**Comment by palob** [comment]
@Foggalong That +/- 2 thing is just due to HSL/RGB conversion.

**Comment by Jacajack** [comment]
@Foggalong I used new baseplate in icon, so gradient is perfectly aligned now (I believe I might have broken something in the old one before).

@palob HSL/RGB conversion was first thing that came to my mind actually. In this case I believe I can leave it, as it is, right?

By the way, again, I'm sorry for bothering you that long with just one icon :P

**Comment by Foggalong** [comment]
@Jacajack No problem, thanks for the contribution! :+1:

**Pull request merged**
