### PR TITLE
Removes unneeded html tags from icons

### LINKED ISSUE #1930: MintInstall missing icons.
mintinstall-numix-circle

I don't know why, but mintinstall is not taking some of numix-circle icons. I think this might be fixed with some symlinking, since most of the categories can be replaced with existing icons. The needed icons are named `applications-*`, as can be seen [here](https://github.com/linuxmint/mintinstall/blob/6ffef49e98ca8aa27f8227b14a492476ea700bbe/usr/lib/linuxmint/mintInstall/mintinstall.py#L1117-L1183). I tried [this](https://github.com/numixproject/numix-icon-theme-circle/pull/1678) but it didn't work. I guess they have to be in "categories" subdirectories. Regular Numix has most of them: try `find /usr/share/icons/Numix/ -name 'applications-*.svg' | cut -d '/' -f 6-`.

Also, how can I clone the repo and install my local version of it with apt, do I have to package it? How do you do it?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10925433-mintinstall-missing-icons?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2750: Mint Software Manager "crippled icons"
Hi.
For some reason there are only colored circles (means that icons were applied, but without images?) in Software Manager. Icons for these categories are also placed in kickoff and they work fine.

screenshot from 2015-12-27 20 19 38

The same behavior:
screenshot from 2015-12-27 21 25 12

Is that a known issue?
Linux Mint 17.3 cinnamon

### PR DESCRIPTION
**Pull request by wa4557**
more details over there: #2750. Should fix #2750 and also an old issue. Fixes #1930 because that's actually the same issue. 

We should take care that for icons added in future no `clipPath` is present since it seems to cause a lot of breakages...

As a rule of thumb: whenever the github preview is not working there is some clipping somewhere involved. (As a nice side effect: the github preview should now work for all icons \o/)

### CODE REVIEW

**Comment by wa4557** [comment]
I also ran the `svgclean` script (the same palob did some time ago) to remove the last traces of the infamous clipping

**Comment by palob** [comment]
OK, there`s a few broken icons:
* Using the CD symbol: ``goobox.svg``, ``kscd.svg``, ``rubyripper.svg``
  (``furiusisomount.svg`` though looks fine

I don't think it's big of an issue, they just need to be readded from master and edited manually.

*Just as a reminder for myself: ``jiten.svg`` suffers the 'special gradient' bug (the one where you can't even alter the colour in Inkscape).
It already did so before this PR and needs a fresh baseplate.*

**Comment by palob** [comment]
Strangely enough the icons aren't broken when viewed in a Qt viewer this time.

**Comment by palob** [comment]
I've finished my first round of scrutiny. No more broken icons found.
I'm no booting into a Kubuntu iso to view the icons in Gwenview.

**Comment by palob** [comment]
Went through all the icons and found one more broken.
All in all the following 7 need manual intervention:
+ broken baseplate: ``basex``, ``nightingale``
+ broken icon: ``goobox``,``indicator-sound-switcher``, ``kaudiocreator``, ``kscd``, ``rubyripper``

Unfortunately there's a merge conflict now.

I'll fix what I've reported to myself above and other issues I've come across in a maintenance PR down the road.

**Comment by wa4557** [comment]
`kscd` is a symlink to `goobox`

**Comment by palob** [comment]
Oops, so it's only six. 
The icons added when resolving the conflict ahve got ``clipPath`` stuff.
I hope we won't get any new ``clipPath`` objects when the baseplates are clean after this PR.
That is when all contributors work with the latest git.

**Comment by wa4557** [comment]
Ok I resolved the last merge conflicts and cleaned also the latest contributions. No clipping left. 

@Foggalong It would be fairly cool if this PR could be merged relatively timely, so that no further conflicts arise.

The next few weeks when merging PR we have to be careful that we don't add new icons with this infamous `<clipPath` tag

**Comment by palob** [comment]
Yeah, Github preview is actually saying something.
But before merging those 6 broken icons need to be repaired (taken from master and ridded of ``clipPath`` objects manually).

**Comment by wa4557** [comment]
I did here: https://github.com/wa4557/numix-icon-theme-circle/commit/0f569fc74ad2738a80697f7b59b2eb89a7580275

**Comment by wa4557** [comment]
Proof (with working github preview): https://github.com/wa4557/numix-icon-theme-circle/blob/0f569fc74ad2738a80697f7b59b2eb89a7580275/Numix-Circle/48x48/apps/goobox.svg

So from my point of view this PR is ready to be merged and actually should be merged asap. 

Thanks for finding all the broken icons @palob!

**Comment by palob** [comment]
:+1: Ready to be merged, thanks for doing this.

**Comment by Foggalong** [comment]
This is some amazing work guys. Really a job well done :)

**Comment by wa4557** [comment]
Don't want to sound cocky but a working ppa would be great now, since this fix again affects a lot of users (almost every Mint user)...

**Comment by palob** [comment]
I'll push my maintenance PR soon, afterwards it's time for a PPA trigger.

**Comment by Foggalong** [comment]
Not at all, we definitely need the PPA back up a and running. Numix are having few admin problems behind the scenes and I'm currently revising for January exams which is why updates are a bit sporadic atm.

**Pull request merged**
