### PR TITLE
This should add support for Linux Mint 17.3 with Cinnamon 2.8

### PR DESCRIPTION
**Pull request by robrobinbin**
Well, not really 'add support', simply improve it a bit... I haven't tested this intensively.

### CODE REVIEW

**Comment by palob** [comment]
Aren't those icons hardoded anymore?

Why did you link ``cs-input-method```to ``empathy``?

I think ``mintinstall`` would better be linked to ``software-center`` or have a dedicated icon in the long run.

**Comment by robrobinbin** [comment]
> Aren't those icons hardcoded anymore?

Some of them still are (I had to edit some .desktop-files), but if I'm not mistaken the most important ones aren't any more (like software center and update)

> Why did you link `cs-input-method` to `empathy`?

The corresponding .desktop-file used `im-chooser` as a logo. This redirects to `empathy`. This could be a mix-up (im == input-method, im == instant messaging), but `cs-input-method` is about language support and stuff, so a speech bubble isn't completely out of place.

> I think mintinstall would better be linked to software-center or have a dedicated icon in the long run.

I have no opinion about this :) Anything round and flattish will look more at home than a lost Faenza-icon

**Comment by zummuz** [comment]
>I think mintinstall would better be linked to software-center or have a dedicated icon in the long run.

Yes, icon name for Software Manager is mintinstall, and system-software-install.svg is a symlink (`lrwxrwxrwx 1 root root 12 Dec 22 16:47 icons/Mint-X/apps/96/system-software-install.svg -> synaptic.svg`) and used by Synaptic Package Manager
>Aren't those icons hardoded anymore?

I guess [no](https://github.com/Foggalong/hardcode-fixer/issues/215#issuecomment-168294414)

**Comment by palob** [comment]
@robrobinbin Is ``preferences-desktop-locale.svg`` used somewhere in Cinnamon settings?
If not I'd link ``cs-input-method`` to that.

Or maybe even better link it to ``translator.svg``.

**Comment by robrobinbin** [comment]
@palob `preferences-desktop-locale.svg` is used already, I was confused for a second and 
thought that Input Methods was used for language in general, is isn't, it is about methods to type characters used in exotic languages (on a non exotic keyboard). 

`translator.svg` looks awesome for this purpose, but for consistency we also should change `im-chooser` to  `translator.svg` then and I don't know which other applications use this icon.

**Comment by palob** [comment]
I think it's safe to change the link for ``im-chooser``. If it's used for any whatsoever instant messaging servise chooser ``translator.svg`` still is a tolerable fit.

**Comment by robrobinbin** [comment]
Updated! The translator icon looks awesome. I'm not super-convinced by the `software-center` icon, but it's definitely better than no icon.

**Pull request merged**
