### PR TITLE
raktpdf-guitarrig5

### PR DESCRIPTION
**Pull request by Geothermal123**
This adds a new icon for Guitar Rig 5 from Native Instruments as well as symlinking from diffpdf to raktpdf because raktpdf does not have an icon.

### CODE REVIEW

**Comment by Geothermal123** [comment]
A slight tweaking of the Guitar Rig 5 icon from my last pull request

**Comment by Foggalong** [comment]
@Geothermal123 the symlink included in this pull is one specifically for your computer, not a relative one as it needs to be to be merged

**Comment by wa4557** [comment]
There are `<clipPath>` tags in this PR. We might want to get rid of them. @Geothermal123 Can you try opening your icon(s) with a text editor and remove everything between `<clipPath` and `</clipPath>` (including the tags) and see if the icons still looks the same?

**Comment by palob** [comment]
It's [those lines](https://github.com/THEGUSPROJECT/numix-icon-theme-circle/blob/a2e6cfb126cf73c83059dd4bdfda49392aa0c663/Numix-Circle/48x48/apps/guitarrig5.svg?short_path=9149e8f#L68-L127).

**Comment by Foggalong** [comment]
You there @Geothermal123?

**Comment by Geothermal123** [comment]
Sorry I didn't respnd sooner. I created a proper symlink and improved the icon to no longer require clipping.

**Comment by Foggalong** [comment]
@Geothermal123 on a design note, the shadow on the G symbol shadow has to follow the same 1px right, 1px down as the pic shadow

**Comment by Foggalong** [comment]
bump @Geothermal123

**Pull request closed without merging**
