### PR TITLE
Fixes #927

### LINKED ISSUE #927: MATE Control Center shows non-circle icons
Most of the icons in MATE Control Center are covered by Numix Circle. As you can see on this screenshot, two icons stick out:

mate-control-center

`Appearance` uses `/apps/preferences-desktop-theme.svg`, while `Windows` uses `/apps/preferences-system-windows.svg`. Is this form intentional or could they be turned into circled versions?

I am asking because similar-looking circled versions of these icons already exist in Numix Circle and were designed for the related Cinnamon Control Center (`/apps/cs-*.svg`). Maybe these could be used for MATE as well?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/2684729-mate-control-center-shows-non-circle-icons?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F514195&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by wa4557**
#927

### CODE REVIEW

**Comment by Foggalong** [comment]
Can we also have these two icons from [@dirtydancing's last comment](https://github.com/numixproject/numix-icon-theme-circle/issues/927#issuecomment-94302432)

**Comment by wa4557** [comment]
Sure, done

**Comment by Foggalong** [comment]
Nice idea, but system-lock-screen and the screensaver are two different preference sections. Maybe copy the moon + stars accross to the lock icon and adjust the colours?

**Comment by wa4557** [comment]
Oh yeah sure did't think of that, I'll do it right away

**Comment by Foggalong** [comment]
Awesome!

**Comment by wa4557** [comment]
Done

**Pull request merged**
