### PR TITLE
Icon for Calligra Gemini

### PR DESCRIPTION
**Pull request by palob**
https://www.calligra.org/gemini/
QML touch interface for Calligra Words/Stage
calligragemini

### CODE REVIEW

**Comment by palob** [comment]
Made the symbol a bit smaller, I think it looks better.
calligragemini

**Comment by Foggalong** [comment]
I can't decide if it needs shifting right slightly to counteract the "triangle" illusion

**Comment by palob** [comment]
It does indeed, it wasn't centered, I had shifted it to the left but 2px was too much with the smaller symbol.
calligragemini

**Comment by Foggalong** [comment]
Much better :+1:

**Pull request merged**
